'use strict';
// Roteiro editorial para aprovação. Os vídeos e o jogo ainda serão produzidos.
const phaseScripts = [
  {
    name:'Imigração', title:'O que atravessa o tempo', location:'Tela 1 · parede lateral esquerda',
    premise:'Uma mala se abre e revela trajetórias. O grupo descobre que uma cidade reúne histórias de quem chegou e de quem já vivia no território.',
    objective:'Reconhecer a diversidade das trajetórias e relacionar objetos a memórias, sem transformar a imigração em uma história única.',
    setting:'Prólogo em ambiente histórico reconstituído; passagem para uma exposição virtual dentro do Castelinho. A cenografia antiga será construída a partir do acervo aprovado, sem usar a arquitetura futura como se fosse de 1915.',
    badge:'Carimbo Imigração · Histórias que se encontram',
    scenes:[
      {id:'IM-01',time:'00:00–00:30',seconds:30,title:'Uma mala, muitas perguntas',visual:'Plano próximo de uma mala fechada. A luz destaca a textura; ao fundo, um ambiente de chegada inspirado em fotografias aprovadas. Câmera estável na altura do olhar. Som discreto de passos e bagagens.',voice:'Uma mala pode guardar objetos. Mas ninguém chega trazendo apenas coisas. Traz lembranças, saberes e a vontade de encontrar um lugar. Antes dessas chegadas, este território já tinha habitantes e histórias. Entre: vamos conhecer algumas dessas trajetórias.',interaction:'Comando “Abrir a mala”. Um único ponto de interação, com indicação visível e locução da instrução.',feedback:'A mala abre e revela três símbolos: fotografia, carta e ferramenta. Se ninguém agir, o mediador pode iniciar o percurso assistido.',production:'Blender: mala animada e cenário. Seedance: plano de ambientação de 8–12 s, repetido com corte discreto apenas enquanto aguarda a escolha. Texto e instruções aplicados na interface.'},
      {id:'IM-02',time:'00:30–01:20',seconds:50,title:'Escolher uma lembrança',visual:'Os três objetos ficam grandes e separados. Ao escolher um, aparece um breve vídeo ilustrativo: encontro familiar, leitura de correspondência ou transmissão de um saber.',voice:'Qual lembrança o grupo quer abrir primeiro? A fotografia aproxima pessoas. A carta atravessa distâncias. A ferramenta acompanha um saber. Os objetos desta cena são símbolos; as histórias reais serão identificadas pelo acervo que vier a compor a exposição.',interaction:'Escolher “Fotografia”, “Carta” ou “Ferramenta”. Cada caminho abre um clipe de 10–15 s e uma legenda de contexto. Apenas uma escolha é necessária; as três reconvergem no mesmo ponto.',feedback:'“Vocês abriram uma memória.” Nenhuma escolha é errada. Não atribuir nacionalidade a alguém pela aparência, roupa ou objeto.',production:'Três clipes alternativos. Fotografia e documento reais entram como imagens preservadas, com crédito; reconstituições recebem a indicação “Cena ilustrativa”.'},
      {id:'IM-03',time:'01:20–02:15',seconds:55,title:'Um território com muitas presenças',visual:'Panorama de paisagem e exposição com três pontos iluminados: “Quem já vivia aqui”, “Quem chegou” e “Histórias que continuam”. Sem mapa fictício de propriedade ou fronteiras étnicas.',voice:'Indígenas, pessoas negras e caboclas já faziam parte deste território. A chegada de migrantes e imigrantes ampliou encontros e também trouxe conflitos. Conhecer Erechim pede escutar diferentes experiências, sem apagar nenhuma delas. Observe os três pontos e descubra uma pergunta em cada um.',interaction:'Selecionar um ponto; depois, o percurso apresenta brevemente os outros dois. As perguntas são: “Quem conta esta história?”, “Qual é a fonte?” e “Que outras vozes precisamos ouvir?”.',feedback:'O conjunto forma um mosaico. Não há ranking de povos ou resposta sobre quem “contribuiu mais”.',production:'Blender: exposição e transições entre pontos fixos. Depoimentos somente com identificação, autorização e edição aprovada; na ausência deles, usar o narrador e perguntas curatoriais.'},
      {id:'IM-04',time:'02:15–03:10',seconds:55,title:'Uma pista que pode ser compartilhada',visual:'A fotografia, a carta e a ferramenta voltam ao centro. Uma legenda ilustrativa destaca pessoas, comunicação e trabalho, sem datas inventadas.',voice:'Guardar um objeto é também guardar perguntas sobre ele. Quem o usou? De onde veio? Como chegou até aqui? Para que uma lembrança se torne parte de uma exposição, precisamos conhecer sua história e a origem das informações.',interaction:'Pergunta: “O que ajuda a contar a história de uma fotografia?” Opções: “Identificar pessoas, lugar e origem” ou “Inventar uma data para completar”.',feedback:'Primeira opção: “Isso ajuda a construir uma memória confiável.” Segunda: “Uma data desconhecida deve continuar identificada como desconhecida.” Permitir nova tentativa sem penalidade.',production:'3DVista: cartão de pergunta. Unity: painel com seleção simples. A resposta conclui a atividade; não exige arrastar objetos com o joystick.'},
      {id:'IM-05',time:'03:10–04:00',seconds:50,title:'Histórias que se encontram',visual:'A mala se transforma visualmente em uma vitrine do memorial virtual. As três lembranças formam o carimbo da fase. Últimos segundos reservados à leitura e orientação da saída.',voice:'Uma cidade não cabe em uma única mala, em uma única família ou em uma única versão. Sua memória cresce quando diferentes histórias podem ser conhecidas. Vocês concluíram Imigração. Levem esta pergunta: que lembrança da sua família ajuda a contar a história de Erechim?',interaction:'“Concluir fase” e “Ver carimbo”. A pergunta final é para conversa, sem coleta obrigatória de dados pessoais.',feedback:'Entregar o carimbo desta fase. A participação nas outras telas é independente; a próxima estação não inicia automaticamente.',production:'Final de 10–15 s mais tela de conclusão. Reset pelo mediador após a saída do grupo; não apagar conquistas de um passaporte individual eventualmente adotado.'}
    ],
    assets:['Mala, carta, ferramenta e moldura como objetos cenográficos; documentos de arquivo separados das peças ilustrativas.','Fotografias e relatos com origem, período, autorização e revisão da representação de diferentes comunidades.','Uma cena de entrada, um panorama da exposição, três clipes de lembranças e um final; locução e legendas em faixas separadas.'],
    prompts:[
      ['IM-A · chegada · 10 s','Usar imagem de referência histórica aprovada e enquadramento do Blender. Reconstituição ilustrativa de uma chegada à região de Erechim no início do século XX. Plano estável de mãos pousando uma mala de viagem. Movimento discreto, iluminação natural. Não criar placas, datas, documentos legíveis, bandeiras ou trajes caricatos. Não alterar a geometria de referência. Sem locução nem texto embutido.'],
      ['IM-B · lembrança · 10–15 s por opção','Gerar três tomadas separadas, mantendo cenário, luz e paleta aprovados: uma fotografia sendo observada; uma carta sendo aberta; uma ferramenta sendo colocada sobre a mesa. A câmera faz aproximação lenta. Não inventar escrita legível nem rostos em documentos. Não simular depoimento real. Usar apenas uma ação por tomada.'],
      ['IM-C · encontro de memórias · 10 s','Partir do render aprovado da vitrine virtual do Castelinho. Luz suave percorre os três objetos cenográficos, câmera fixa, movimento mínimo de partículas. Preservar janelas, paredes e proporções. Deixar a área central livre para o carimbo inserido posteriormente. Sem textos gerados.']
    ],
    implementation:'Base em 3DVista: ambiente de exposição com pontos selecionáveis, vídeos em janelas e uma pergunta. A caminhada livre é opcional; o modo guiado por pontos fixos exige menos comandos. Em Unity, o mesmo roteiro pode usar inspeção de objetos e câmera em primeira pessoa.',
    review:'A abertura é uma criação narrativa, não o relato de uma família específica. As presenças anteriores e a diversidade serão revisadas com o Arquivo Histórico e representantes das comunidades. A revista orienta os espaços futuros, não comprova a aparência dos cenários antigos.',
    sources:[['Arquivo Histórico Municipal · fatos da história de Erechim','https://www.pmerechim.rs.gov.br/noticia/19455/artigo-fatos-marcantes-de-nossa-histria'],['IBGE · histórico de Erechim','https://biblioteca.ibge.gov.br/index.php/biblioteca-catalogo?id=31435&view=detalhes']],
    pages:'Revista Castelinho 2025, pp. 15 e 18: memorial, exposição multimídia e educação patrimonial como referências para a ambientação virtual.'
  },
  {
    name:'Comissão de Terras',title:'O mapa guarda perguntas',location:'Tela 2 · fundo esquerdo',
    premise:'O grupo entra no Castelinho e encontra uma mesa com mapa, registro e instrumento de medição. A missão é reunir as pistas que ajudam a compreender a antiga Comissão de Terras.',
    objective:'Entender a função histórica do edifício e aprender a ler documentos como fontes, com contexto e limites.',
    setting:'Exterior e uma sala histórica reconstituída no GLB. Mobiliário, mapa e instrumentos precisam de referência documental; o modelo atual fornece a geometria, não a comprovação da disposição antiga.',
    badge:'Carimbo Comissão de Terras · Ler o território',
    scenes:[
      {id:'CT-01',time:'00:00–00:30',seconds:30,title:'Entre na antiga sede',visual:'A fachada aparece em uma reconstrução baseada no modelo e em imagens de época. A câmera se aproxima lentamente da entrada e para antes de cruzá-la. Porta destacada.',voice:'Este é o Castelinho, antiga sede da Comissão de Terras do Estado. Inaugurado em 20 de abril de 1915, o prédio guarda parte da história da organização do território. Hoje, vocês vão observar pistas dessa história. Abram a porta e conheçam a mesa de trabalho.',interaction:'“Entrar”. A câmera vai para uma posição segura na sala; não exigir deslocamento até a porta com um controle ainda não calibrado.',feedback:'A mesa se ilumina. Identificar a cena como reconstituição histórica proposta.',production:'Blender: fachada e abertura da porta. Usar a data da revista, p. 3; não tratar 1916 como data de inauguração.'},
      {id:'CT-02',time:'00:30–01:20',seconds:50,title:'Escolha por onde investigar',visual:'Três objetos: mapa, livro de registros e instrumento de medição. Um único objeto é destacado por vez, com som curto de seleção.',voice:'Um mapa representa o espaço. Um registro documenta informações. Um instrumento ajuda a medir. Essas pistas se complementam, mas nenhuma conta tudo sozinha. Escolham por onde começar e observem o que cada uma permite descobrir.',interaction:'Escolher um dos três objetos. O mapa amplia; o livro abre em uma reprodução aprovada; o instrumento mostra uma animação explicativa de 8–12 s. Os caminhos se reencontram.',feedback:'“Primeira pista observada.” A identidade do instrumento e a reprodução do documento serão confirmadas antes de gravar a locução específica.',production:'Três mídias alternativas e uma animação de detalhe. Textos de mapas e registros inseridos na edição, nunca gerados por IA como prova histórica.'},
      {id:'CT-03',time:'01:20–02:15',seconds:55,title:'Do desenho ao território',visual:'Um detalhe de mapa aprovado ocupa a mesa. Duas áreas grandes indicam “Representação” e “Território”. Uma linha animada conecta o documento a um cenário ilustrativo, sem redesenhar limites reais.',voice:'O trabalho da Comissão esteve ligado à divisão e à distribuição de terras da região. Mas o território não era uma folha em branco: havia pessoas, usos e relações anteriores. Ler esses documentos exige observar também seus limites e perguntar quais experiências ficaram fora do papel.',interaction:'Pergunta: “Um mapa conta sozinho toda a história de um lugar?” Opções: “Sim, ele mostra tudo” ou “Não, precisa de outras fontes e vozes”.',feedback:'Segunda opção: “Documentos precisam ser contextualizados.” Primeira: “O mapa é uma fonte importante, mas não mostra todas as experiências.” Permitir tentar novamente.',production:'Evitar transformar a distribuição de terras em um prêmio do jogo ou simular a atribuição de propriedades a visitantes. O desafio é de interpretação documental.'},
      {id:'CT-04',time:'02:15–03:10',seconds:55,title:'Abrir uma janela de investigação',visual:'O mapa volta à mesa; ao lado surge uma fotografia documentada da antiga sede. Dois botões: “Observar detalhe” e “Ver contexto”. A câmera permanece fixa durante a leitura.',voice:'Uma janela, uma varanda, um móvel: pequenos detalhes ajudam a investigar o passado. Compare a imagem com o modelo. Algumas partes podem ter mudado. Quando a informação não está confirmada, a exposição precisa mostrar essa dúvida, em vez de completar a história por imaginação.',interaction:'Selecionar um detalhe da fotografia previamente demarcado. Um sobreposto mostra a referência e o que foi reconstruído no modelo.',feedback:'“Detalhe registrado.” Se a imagem não tiver data ou autoria confirmada, a legenda informa essa condição. A semelhança visual não vale como comprovação.',production:'Blender: câmera com enquadramento próximo ao documento. 3DVista: alternância entre imagens; Unity: comparação equivalente. Não depender de slider fino.'},
      {id:'CT-05',time:'03:10–04:00',seconds:50,title:'O edifício também é documento',visual:'A sala de trabalho dá lugar a uma vitrine contemporânea virtual. Mapa, livro e instrumento se organizam como peças de exposição. Surge o carimbo.',voice:'O Castelinho guardou documentos, atividades e muitas mudanças. Preservar o prédio ajuda a manter essas perguntas acessíveis. Vocês concluíram Comissão de Terras. Um mapa orienta um caminho; a memória ganha sentido quando aprendemos a lê-lo junto com outras histórias.',interaction:'“Concluir fase”. Cartela opcional “Conheça também A Cidade”, sem transferir a sessão para outra tela.',feedback:'Carimbo da fase e orientação do mediador para a próxima rodada.',production:'Final independente, sem exigir ter completado Imigração. Reservar tempo para leitura e troca do grupo.'}
    ],
    assets:['GLB com porta e objetos separados; uma sala histórica validada, com limites de circulação.','Mapa, livro e fotografia digitalizados com metadados; instrumento identificado por especialista.','Uma entrada, três detalhes alternativos, uma comparação visual e um final; legendas documentais fora da geração por IA.'],
    prompts:[
      ['CT-A · chegada à sede · 10–12 s','Usar render do Blender como referência estrutural e fotografia de época aprovada como referência histórica. Aproximação lenta da entrada do Castelinho de Erechim, câmera na altura dos olhos. Preservar exatamente gabarito, ornamentos, janelas e porta. Sem mudar época, criar letreiros ou acrescentar pessoas reconhecíveis. Sem texto nem locução.'],
      ['CT-B · mesa de trabalho · 10 s','Plano médio estável da mesa histórica aprovada. Uma pessoa fictícia, vista de costas e sem fala, examina um mapa cuja arte será substituída pela digitalização real na composição. Movimento discreto dos braços, sem deformar mãos nem objetos. Não representar funcionário nominal ou documento como autêntico.'],
      ['CT-C · detalhe do instrumento · 8 s','Usar o instrumento validado e o render fornecido. Movimento de câmera muito lento revelando material e escala. Não modificar o mecanismo, não criar medição numérica, não animar funcionamento não documentado. Fundo neutro da mesma sala, sem textos.']
    ],
    implementation:'No 3DVista, objetos separados podem funcionar como pontos de interação e acionar animações, imagens e perguntas. Em Unity, usar os mesmos objetos com seleção por foco central; a lógica adicional será programada. Começar por uma sala e uma pergunta para validar o GLB e o controle.',
    review:'Confirmar a forma histórica de cada sala, o instrumento e os documentos. A data de inauguração vem da revista. A interpretação sobre o território deve incluir as populações anteriores e evitar a ideia de terra vazia.',
    sources:[['Arquivo Histórico Municipal · sede da Colônia e diversidade de habitantes','https://www.pmerechim.rs.gov.br/noticia/19455/artigo-fatos-marcantes-de-nossa-histria']],
    pages:'Revista Castelinho 2025, pp. 3–4: inauguração, função original e mudanças de uso; p. 15: memorial previsto.'
  },
  {
    name:'A Cidade',title:'A mesma janela, outros tempos',location:'Tela 3 · fundo direito',
    premise:'Uma janela virtual se abre para Erechim. O grupo compara registros da cidade, encontra permanências e percebe transformações.',
    objective:'Relacionar a história do Castelinho à formação urbana e reconhecer fotografias, mapas e relatos como fontes complementares.',
    setting:'Ponto de observação virtual no Castelinho e uma exposição de imagens da cidade. A vista real do modelo será conferida; quando um local não puder ser visto dali, aparece em um painel, não como uma falsa vista da janela.',
    badge:'Carimbo A Cidade · Olhar que reconhece',
    scenes:[
      {id:'CI-01',time:'00:00–00:30',seconds:30,title:'Abra a janela',visual:'Interior do Castelinho em primeira pessoa. A janela abre para uma vista contemporânea compatível com a orientação do modelo. Sons urbanos baixos e imagem sem deslocamento brusco.',voice:'Uma janela parece mostrar sempre o mesmo lugar. Mas a cidade muda, e cada geração deixa marcas. Erechim se desenvolveu ligada à ferrovia e se tornou município em 1918. Vamos comparar imagens para perceber o que mudou e o que continua fazendo parte da paisagem.',interaction:'“Abrir a janela”. Exibir o primeiro par de imagens aprovado, com identificação do lugar e período confirmado.',feedback:'O grupo encontra um ponto de observação. Não simular um voo livre sobre uma cidade ainda não modelada.',production:'Blender: câmera e janela. Paisagem real ou panorama licenciado; a vista histórica é identificada como documento ou reconstituição.'},
      {id:'CI-02',time:'00:30–01:20',seconds:50,title:'Reconheça uma permanência',visual:'Duas imagens do mesmo local, em enquadramentos comparáveis. Três áreas de escolha grandes, preparadas a partir de elementos realmente presentes nas duas fotografias.',voice:'Olhem com calma. Entre essas duas imagens, o tempo passou. Qual detalhe ajuda a reconhecer o lugar? Procurem uma forma, um alinhamento ou um edifício que permaneceu. A pista será escolhida a partir das fotografias confirmadas para a exposição.',interaction:'Selecionar o detalhe comum. O elemento exato e as alternativas só serão fixados após receber o par de imagens do acervo.',feedback:'Acerto: sobreposição destaca a correspondência. Outra escolha: “Compare novamente este detalhe”; oferecer a área correta como pista, sem perder pontos.',production:'Comparação documental editada no Blender ou no compositor. Não animar a foto original para que pareça filmagem de arquivo.'},
      {id:'CI-03',time:'01:20–02:15',seconds:55,title:'Escolha um olhar sobre a cidade',visual:'Três portas de conteúdo: “Caminhos”, “Encontros” e “Paisagem”. Cada uma abre uma breve sequência com material autorizado: circulação e ferrovia; vida coletiva; mudanças urbanas.',voice:'Uma cidade também se constrói nos caminhos, no trabalho e nos encontros. Que aspecto vocês querem observar? A escolha muda a próxima cena, mas todas voltam à mesma pergunta: como as pessoas transformam o lugar onde vivem?',interaction:'Escolher uma das três portas. Vídeo de 12–18 s e uma legenda curta; retorno automático ao ponto comum.',feedback:'“Um novo olhar foi aberto.” Evitar descrever um evento, edifício ou data que não esteja identificado no material usado.',production:'Três clipes alternativos. IA para ambientações ilustrativas; arquivo real preservado em quadros identificados. Música instrumental discreta, sem vozes competindo com a narração.'},
      {id:'CI-04',time:'02:15–03:10',seconds:55,title:'O que a cidade precisa guardar?',visual:'Uma fotografia histórica e um modelo contemporâneo se apresentam em planos separados. Três símbolos: “Edifícios”, “Documentos” e “Saberes”.',voice:'A memória urbana vive nas construções, mas também nos documentos e nos conhecimentos compartilhados. Um prédio pode ser restaurado. Uma fotografia pode ser conservada. Um saber pode ser transmitido. O cuidado com a cidade aproxima essas três formas de preservar.',interaction:'Pergunta: “Qual conjunto ajuda a preservar a memória?” Opções: “Só a fachada” ou “Edifícios, documentos e saberes”.',feedback:'Segunda opção: os três símbolos se conectam. Primeira: “A fachada é importante; outras memórias também precisam de cuidado.” Nova tentativa assistida.',production:'Animação gráfica simples, grande e legível. Nenhuma mecânica de demolição, compra de terrenos ou pontuação econômica.'},
      {id:'CI-05',time:'03:10–04:00',seconds:50,title:'Você reconhece. Você participa.',visual:'A janela retorna ao presente. O carimbo se forma sobre uma composição das imagens aprovadas. A cidade permanece visível atrás, sem movimento acelerado.',voice:'Reconhecer a cidade é também aprender a cuidar dela. O Castelinho é uma das portas para essa conversa entre passado e presente. Vocês concluíram A Cidade. Quando saírem, observem um lugar de Erechim com uma nova pergunta: que histórias ainda podemos conhecer aqui?',interaction:'“Concluir fase”. Pergunta para conversa entre os cinco participantes; sem resposta pessoal obrigatória.',feedback:'Carimbo A Cidade. Sugerir a fase Castelinho para descobrir os ambientes futuros.',production:'Conclusão independente. O vídeo termina em quadro estável para orientar a saída e a troca.'}
    ],
    assets:['Dois pares de fotografias do mesmo lugar, com datas ou períodos confirmados e autorização de uso.','Uma vista atual compatível com a janela do GLB; painel alternativo quando a orientação não coincidir.','Uma abertura, comparação em duas versões, três clipes temáticos e final; mapa somente quando validado.'],
    prompts:[
      ['CI-A · janela · 10 s','Partir do render aprovado do interior e da vista real de Erechim fornecida. Câmera fixa na altura dos olhos, janela se abre suavemente. Preservar orientação, linha do horizonte e todos os marcos urbanos. Não acrescentar edifícios, montanhas, igrejas ou monumentos. Sem textos.'],
      ['CI-B · vida urbana · 12 s','Reconstituição ilustrativa baseada em fotografia e período aprovados. Pequenos movimentos de pessoas fictícias no enquadramento original, câmera estável. Preservar fachadas e traçado visível. Não criar letreiros, datas, veículos de outra época ou personagens reais. A imagem será apresentada como reconstituição, não como filmagem histórica.'],
      ['CI-C · paisagem no presente · 10 s','Usar imagem contemporânea autorizada de Erechim. Movimento ambiental discreto, câmera parada, luz coerente com a referência. Manter integralmente arquitetura, proporções e horizonte. Sem transformação automática de um prédio em outro; a comparação temporal será editada separadamente.']
    ],
    implementation:'No 3DVista, o essencial é alternar imagens e abrir vídeos a partir de três escolhas; isso funciona sem modelar a cidade inteira. Unity permite uma área urbana caminhável, mas exigiria modelagem, otimização e colisões adicionais. Para a estreia, a janela e os painéis mantêm o escopo viável.',
    review:'Conferir cada par de imagens e a orientação da vista. Usar 1918 como referência à criação do município, sem reproduzir números de decreto divergentes entre fontes. Não gerar uma cidade genérica e chamá-la de Erechim documental.',
    sources:[['IBGE · formação histórica de Erechim','https://biblioteca.ibge.gov.br/index.php/biblioteca-catalogo?id=31435&view=detalhes'],['Arquivo Histórico Municipal · cinco nomes e transformações da cidade','https://www.pmerechim.rs.gov.br/noticia/16503/erechim-104-anos-de-historia-em-cinco']],
    pages:'Revista Castelinho 2025, p. 19: ático com vista para a cidade e proposta de exposição tecnológica baseada no acervo.'
  },
  {
    name:'Castelinho',title:'Uma casa para o próximo capítulo',location:'Tela 4 · parede lateral direita',
    premise:'Passado, restauro e futuro se encontram. O grupo atravessa uma visita virtual aos ambientes previstos e escolhe como gostaria de vivenciar o Castelinho.',
    objective:'Entender por que preservar técnicas e edifício, conhecer os usos futuros previstos e reconhecer a participação da comunidade nessa continuidade.',
    setting:'Modelo arquitetônico futuro do Castelinho como base principal. Três marcações persistentes distinguem “Registro histórico”, “Restauro em andamento” e “Ambiente previsto no projeto”.',
    badge:'Carimbo Castelinho · A história continua',
    scenes:[
      {id:'CA-01',time:'00:00–00:30',seconds:30,title:'Um prédio que permanece',visual:'Fotografia histórica identificada, registro recente autorizado da obra e render futuro aparecem em sequência, com suas três legendas. Corte entre imagens; evitar uma transformação por IA que invente etapas do restauro.',voice:'O Castelinho atravessou diferentes usos e transformações. Hoje, seu restauro busca conservar o edifício e preparar novas possibilidades de encontro. Nesta visita, vamos distinguir o que é registro do passado, o que pertence à obra e o que está previsto para o futuro.',interaction:'“Começar visita”. As três legendas são lidas e permanecem associadas às respectivas imagens.',feedback:'Uma linha visual conecta as três etapas. Esta apresentação não anuncia data de reabertura.',production:'Atualizar a fotografia da obra antes da feira. A reportagem de 22/07/2026 contextualiza o restauro; não substitui a vistoria ou a atualização oficial de novembro.'},
      {id:'CA-02',time:'00:30–01:05',seconds:35,title:'Preservar a madeira e o saber',visual:'Detalhe de madeira e encaixe aprovado pela equipe de restauro, seguido de um registro autorizado de trabalho. Um modelo separado mostra o encaixe sem simular uma instrução de execução.',voice:'A preservação também depende de conhecimentos transmitidos entre gerações. O projeto valoriza a madeira, os encaixes e os saberes de quem trabalha com essas técnicas. Cuidar do Castelinho envolve conservar a construção e manter esse conhecimento vivo.',interaction:'Escolher “O que precisa ser preservado?”: “Só a aparência” ou “O edifício e os saberes”.',feedback:'Segunda opção: “O cuidado reúne matéria e conhecimento.” Outra: explicação curta e nova tentativa. Não afirmar que o prédio inteiro foi construído sem nenhum prego.',production:'Detalhe técnico fiel ao material validado. Não usar IA para inventar uma operação real de restauro. Oficina de carpintaria aparece adiante como uso previsto, não como nova quinta fase.'},
      {id:'CA-03',time:'01:05–01:50',seconds:45,title:'Entrar, conhecer e permanecer',visual:'Percurso guiado no térreo futuro: recepção e acesso, exposição temporária, memorial, pequena loja de lembranças e artesanato, café e varandas. Cada parada recebe nome legível.',voice:'No térreo, o projeto prevê recepção, informações ao visitante e espaços para conhecer a história. Exposições temporárias e um memorial poderão aproximar o público do acervo. A pequena loja, o café e as áreas de estar completam a proposta de permanência e convivência.',interaction:'Escolher “Conhecer histórias” ou “Encontrar pessoas”. A primeira destaca memorial e exposições; a segunda destaca café e varandas. Uma breve montagem mostra os demais pontos, e os caminhos se reencontram.',feedback:'Ambas são formas propostas de ocupar o edifício. Exibir “Ambientes previstos · Revista 2025, pp. 14–15”.',production:'Blender: posições de câmera no modelo aprovado. Trocas por corte ou passagem suave, sem atravessar paredes. A acessibilidade é apresentada conforme o projeto, sem prometer que já esteja executada.'},
      {id:'CA-04',time:'01:50–02:30',seconds:40,title:'Uma casa para aprender',visual:'Cartela de pavimentos orienta a visita. Primeiro subsolo: salas multiuso com painéis móveis. Anexo do segundo subsolo: oficina técnica. Primeiro pavimento: sala multimídia e espaço infantil.',voice:'As salas multiuso foram pensadas para aulas, oficinas e ensaios. O projeto também prevê oficina técnica, sala multimídia e espaço infantil de educação patrimonial. São possibilidades para aprender, criar e compartilhar. Qual dessas atividades o grupo gostaria de conhecer primeiro?',interaction:'Selecionar “Oficinas”, “Multimídia” ou “Espaço infantil”. Exibir a parada correspondente por 8–10 s; depois, apresentar miniaturas identificadas das outras duas.',feedback:'Não há opção errada. A escolha expressa interesse e não registra inscrição, disponibilidade de vaga ou programação confirmada.',production:'Demais áreas de apoio, sanitários e administração ficam identificadas no mapa de pavimentos acessível dentro desta fase. A visita principal prioriza os espaços de uso cultural.'},
      {id:'CA-05',time:'02:30–03:20',seconds:50,title:'A memória encontra novas linguagens',visual:'Subida virtual orientada para o ático. Exposição tecnológica ilustrativa: mesa interativa, projeção e visualização do acervo. Transição para jardins, caminhos, decks e áreas de convivência.',voice:'No ático, a proposta aproxima o acervo de recursos digitais: imagens, sons e experiências interativas. Do lado de fora, caminhos e decks ampliam os espaços de convivência e pequenas apresentações. A tecnologia pode ajudar a contar histórias; o encontro entre pessoas dá continuidade a elas.',interaction:'Escolher “Explorar o acervo” ou “Conhecer os jardins”. O caminho escolhido recebe destaque; a outra possibilidade aparece em uma síntese antes da conclusão.',feedback:'Mostrar “Recursos previstos, sujeitos à implantação”. Holografia é apresentada como recurso previsto na revista, não como equipamento já comprado ou funcional.',production:'Cenário fiel ao projeto; conteúdos de telas aplicados na pós-produção. Não gerar uma instalação tecnológica futurista que ultrapasse os ambientes documentados.'},
      {id:'CA-06',time:'03:20–04:00',seconds:40,title:'A história continua com a comunidade',visual:'Retorno à fachada futura, alternada com imagem real autorizada de mobilização comunitária. Sem reproduzir vozes ou rostos de dirigentes por IA. Carimbo da fase e convite final.',voice:'Preservar também é uma construção coletiva. A Associação Amigos do Castelinho reúne a comunidade em torno da recuperação, conservação e valorização desse patrimônio. Vocês concluíram Castelinho. O futuro que vimos é uma proposta para ser construída e vivida. Entre. Descubra. Faça parte da história.',interaction:'“Concluir fase”. Quem passou pelas quatro estações pode receber o reconhecimento “Guardião do Castelinho”, mediante verificação do passaporte pela equipe.',feedback:'Uma única fase concede seu próprio carimbo. O título de Guardião não é liberado automaticamente só por assistir à fase 4.',production:'Final de 10–15 s e tempo de leitura. Mensagem institucional final e eventual QR Code precisam de aprovação da Associação; sem cobrança, cadastro ou doação como condição para concluir.'}
    ],
    environments:[
      ['Térreo · pp. 14–15','Recepção, informações turísticas, acessibilidade proposta, exposições temporárias, memorial, lembranças e artesanato, café e varandas.'],
      ['1º subsolo · p. 16','Salas multiuso para aulas, oficinas e ensaios; painéis móveis, copa, sanitários e sala administrativa no anexo.'],
      ['2º subsolo · p. 17','Áreas de apoio e sanitários, acesso pelo elevador e decks; oficina técnica no anexo.'],
      ['1º pavimento · p. 18','Exposição multimídia, espaço infantil de educação patrimonial, administração, reserva técnica e apoio.'],
      ['Ático · p. 19','Vista para a cidade e exposição tecnológica: mesas interativas, projeções e recursos de holografia previstos. Digitalização do acervo como base do conteúdo.'],
      ['Área externa · pp. 9–13','Jardins, percursos, pergolados, áreas de estar, decks e espaços para pequenas apresentações. Não fixar metragem externa: a revista apresenta valores diferentes no programa e na implantação.']
    ],
    assets:['GLB revisado por pavimento, preservando a fachada fornecida, aberturas, acessos e proporções dos ambientes previstos.','Fotografias autorizadas do passado e do restauro, detalhe construtivo validado e registro da atuação comunitária.','Seis blocos de montagem, cinco clipes alternativos de escolhas, mapa de pavimentos e final. Recepção, memorial, café, salas, espaço infantil, ático e jardins precisam de enquadramentos próprios.'],
    prompts:[
      ['CA-A · recepção futura · 10 s','Usar render e movimento de câmera do Blender como referência. Visualização arquitetônica do térreo futuro do Castelinho: recepção e passagem para exposição, conforme modelo aprovado. Movimento muito lento, luz acolhedora, poucas pessoas fictícias ao fundo. Preservar integralmente paredes, acessos, balcões e ornamentos. Sem letreiros ou alterações arquitetônicas.'],
      ['CA-B · aprender e criar · 8–10 s por ambiente','Criar tomadas separadas para sala multiuso, multimídia e espaço infantil, cada uma usando seu render aprovado. Pessoas fictícias realizam ações discretas de observação e aprendizagem. Não inventar equipamentos nem alterar circulação. Adultos acompanham as crianças. Sem fala, sem texto, sem rosto de pessoa real.'],
      ['CA-C · ático e jardins · 10–12 s por ambiente','Duas tomadas independentes, baseadas nos renders do projeto: ático com dispositivos expositivos previstos; jardins com decks e vegetação existentes no modelo. Câmera fixa ou deslocamento muito lento. Preservar escala, estrutura e posição dos elementos. Telas neutras para composição posterior. Sem hologramas fantasiosos, novos pavimentos ou obras adicionais.']
    ],
    implementation:'Priorizar o GLB e os renders do Blender nesta fase, pois a geometria do futuro é parte central da proposta. Em 3DVista, usar pontos de vista por pavimento, escolhas e vídeos. Unity permite continuidade de caminhada e transições controladas, com trabalho adicional de navegação, acessibilidade e desempenho.',
    review:'Todos os ambientes são previstos na revista de 2025, não entregas confirmadas. A fase 4 do game não é a fase 4 do cronograma de obras. Validar com a responsável pelo restauro quais itens do projeto continuam vigentes antes da gravação. Não usar prazos e valores de reportagens antigas como situação atual.',
    sources:[['Prefeitura · apresentação da Associação ao Poder Público · 27/03/2025','https://www.pmerechim.rs.gov.br/noticia/20318/associacao-amigos-do-castelinho-e-apresentada-ao-poder-publico'],['Rádio Virtual · entrevista sobre restauro e futuro · 22/07/2026','https://virtual.fm.br/restauracao-do-castelinho-resgata-a-historia-de-erechim-e-prepara-espaco-para-as-proximas-geracoes/'],['Jornal Bom Dia · criação da Associação · 15/03/2025','https://jornalbomdia.com.br/noticia/77458/criada-a-associacao-amigos-do-castelinho'],['AU Online · mobilização para fundação · 27/02/2025','https://auonline.com.br/noticia/vereadora-carla-talgatti-mobiliza-comunidade-para-a-fundacao-da-associacao-amigos-do-castelinho/125055'],['Jornal Bom Dia · contexto anterior de mobilização','https://jornalbomdia.com.br/noticia/68076/associacao-dos-amigos-do-castelinho-solucao-para-salvar-o-patrimonio-historico']],
    pages:'Revista Castelinho 2025, pp. 6–19: técnicas, programa e ambientes futuros. A p. 20 apresenta etapas de implantação; elas não equivalem às quatro fases do game.'
  }
];
