// Draft data for Interactive Video
// Auto-generated by SCORM export
// Video ID: cd60d2823d4049f0b13c28bbb1b4b13e
// Interactive Video ID: 3de1409a8c65409fa249f1daf5b39e62

window.DRAFT_DATA = {
  "metadata": {
    "2MedGmgD": {
      "url": "s3://heygen-resources-prod/text_to_speech/7097eee25a5f40ea8e0b4bc549fefaa0/m2oepJCLyzU9OTVL2zev/id=efe5f1e4-75b9-49e3-a229-97e49418d18a.wav",
      "hvml": null,
      "seed": null,
      "type": "tts",
      "error": null,
      "words": [
        {
          "word": "<start>",
          "end_time": 0.0,
          "start_time": 0.0
        },
        {
          "word": "Vamos",
          "end_time": 0.799,
          "start_time": 0.319
        },
        {
          "word": "à",
          "end_time": 0.959,
          "start_time": 0.859
        },
        {
          "word": "primeira",
          "end_time": 1.5,
          "start_time": 1.0
        },
        {
          "word": "missão:",
          "end_time": 1.979,
          "start_time": 1.539
        },
        {
          "word": "Prevenir.",
          "end_time": 3.48,
          "start_time": 2.74
        },
        {
          "word": "Na",
          "end_time": 4.579,
          "start_time": 4.519
        },
        {
          "word": "sala",
          "end_time": 4.92,
          "start_time": 4.719
        },
        {
          "word": "de",
          "end_time": 5.119,
          "start_time": 5.019
        },
        {
          "word": "aula,",
          "end_time": 5.699,
          "start_time": 5.219
        },
        {
          "word": "o",
          "end_time": 5.779,
          "start_time": 5.759
        },
        {
          "word": "cuidado",
          "end_time": 6.399,
          "start_time": 5.879
        },
        {
          "word": "começ",
          "end_time": 6.779,
          "start_time": 6.42
        },
        {
          "word": "a",
          "end_time": 6.94,
          "start_time": 6.92
        },
        {
          "word": "antes.",
          "end_time": 7.48,
          "start_time": 7.059
        },
        {
          "word": "Assista",
          "end_time": 8.699,
          "start_time": 8.239
        },
        {
          "word": "ao",
          "end_time": 8.859,
          "start_time": 8.72
        },
        {
          "word": "vídeo",
          "end_time": 9.159,
          "start_time": 8.899
        },
        {
          "word": "a",
          "end_time": 9.26,
          "start_time": 9.179
        },
        {
          "word": "seguir.",
          "end_time": 9.659,
          "start_time": 9.319
        },
        {
          "word": "<break time=\"0.5s\"/>",
          "end_time": 10.159,
          "start_time": 9.659
        },
        {
          "word": "<end>",
          "end_time": 10.656009070294784,
          "start_time": 10.656009070294784
        }
      ],
      "duration": 10.656009070294784,
      "voice_id": "m2oepJCLyzU9OTVL2zev",
      "element_id": "2MedGmgD",
      "request_id": null,
      "auto_engine": null,
      "used_engine": "mockingbird",
      "audio_duration": null,
      "item_needs_tts": false,
      "next_request_ids": [],
      "next_request_text": null,
      "previous_request_ids": [],
      "previous_request_text": null,
      "caption_override_words": null,
      "next_request_audio_url": null,
      "is_generated_in_workflow": true,
      "previous_request_audio_url": null
    },
    "3uh8ldCz": {
      "fps": null,
      "hvml": null,
      "name": "Elis in the library classroom",
      "type": "avatar",
      "width": 2752,
      "height": 1536,
      "kit_id": null,
      "face_id": null,
      "premium": null,
      "preview": {
        "normal": {
          "src": "https://files2.heygen.ai/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP?Expires=1790019941&Signature=i~JteEf-zIfO4goKnjapXqedSTkcp3NUCOauiqE0Cb5HOorc1yfYLOrDsDBA5BEbURei1PqmcZrFJoNWQJCXedhGSZjzn~lvxR5mp~2t7ab7GedIfcEGJoF3BWrIY~LIB2JFscgzG1dkw4nLcADF4FxmwEGdZQNx54GXtsxFTg~G3t-7i3Zxxbaa1v3u~-1aAI29UqSFhrwZgqiy2xUeh3grPjyZ4H3p3bekyuJ6w-iv6SZPImH3Fjj9R3bhVDGqATSlX-3CHLIMVcSLnRN9VP9qymMSZfuVzHlfVHjI636qIBdpQyz4Pbrc3~Z41cgQEmtdmHI1lEPqml7nvw08cw__&Key-Pair-Id=K38HBHX5LX3X2H",
          "size": {
            "width": 2752.0,
            "height": 1536.0
          }
        },
        "spotlight": null
      },
      "face_url": null,
      "faceswap": null,
      "gestures": null,
      "position": {
        "type": "center",
        "offset": {
          "x": 0.0,
          "y": 0.0
        }
      },
      "crop_rect": {
        "circle": {
          "x": 477.8135986328125,
          "y": 281.70452880859375,
          "width": 654.9371337890625,
          "height": 654.9371337890625
        },
        "close_up": {
          "x": 145.283203125,
          "y": 199.9940185546875,
          "width": 1309.874267578125,
          "height": 1309.874267578125
        }
      },
      "enable_4k": false,
      "has_alpha": false,
      "is_motion": false,
      "outfit_id": null,
      "pose_name": "Elis in the library classroom",
      "element_id": "3uh8ldCz",
      "is_private": true,
      "avatar_name": "Elis in the library classroom",
      "avatar_type": "photo_avatar",
      "original_top": null,
      "natural_width": 2752,
      "original_left": null,
      "original_size": null,
      "webm_eligible": null,
      "enable_enhance": true,
      "enable_matting": true,
      "natural_height": 1536,
      "available_style": {
        "circle": true,
        "normal": true,
        "close_up": true
      },
      "avatar_state_id": "2d0d7a898328477d9f0e92a71fd840d0",
      "crop_box_crop_x": {
        "normal": 0.0,
        "close_up": 0.0
      },
      "blurred_lips_mp4": "",
      "avatar_group_name": "Elis",
      "blurred_lips_webm": "",
      "preview_image_url": "s3://heygen-product/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP",
      "preview_video_url": "",
      "support_avatar_iv": true,
      "enable_eye_contact": false,
      "is_avatar_iv_motion": false,
      "processed_image_url": "s3://heygen-product/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP",
      "enable_change_outfit": null,
      "spotlight_mode_width": null,
      "photo_avatar_metadata": {
        "photar_version": "V3"
      },
      "spotlight_mode_height": null,
      "is_incomplete_metadata": null,
      "original_transformation": null,
      "unlimited_mode_disabled": false,
      "spotlight_mode_crop_rect": null,
      "gesture_preprocessing_state": null,
      "unlimited_mode_disabled_reason": null
    },
    "6SVkeGR7": {
      "url": "s3://heygen-resources-prod/video/bc0b766f20e84136acfaf40b2dfc70b5/original.mp4",
      "hvml": null,
      "type": "video",
      "width": 1920,
      "height": 1080,
      "duration": 30.08,
      "position": null,
      "provider": "user_upload-3ff8f7f47b0e41c38a94c282ca9bdafe",
      "variants": {
        "medium": {
          "key": "s3://heygen-resources-prod/simple_uploads/7097eee25a5f40ea8e0b4bc549fefaa0/7097eee25a5f40ea8e0b4bc549fefaa0/5247737cc79840329d68def8854966df/professor1.mp4_thumbnail.jpg",
          "name": "professor1.mp4",
          "width": 1920,
          "height": 1080,
          "thumbnail": "s3://heygen-resources-prod/simple_uploads/7097eee25a5f40ea8e0b4bc549fefaa0/7097eee25a5f40ea8e0b4bc549fefaa0/5247737cc79840329d68def8854966df/professor1.mp4_thumbnail.jpg",
          "version_id": null
        }
      },
      "background": {
        "top": 540,
        "left": 960,
        "cropX": 0.0,
        "cropY": 0.0,
        "width": 1920.0,
        "height": 1080.0,
        "rotate": 0,
        "scaleX": 1.0,
        "scaleY": 1.0
      },
      "element_id": "6SVkeGR7",
      "asset_source": "user_upload",
      "original_top": 540,
      "original_left": 960,
      "original_size": {
        "fit": "none",
        "crop": {
          "top": null,
          "left": null,
          "right": null,
          "bottom": null
        },
        "scale": {
          "x": 1.0,
          "y": 1.0
        }
      },
      "original_transformation": {
        "rotate": {
          "angle": 0.0
        }
      }
    },
    "HTn4ew51": {
      "hvml": null,
      "type": "interactive",
      "width": 0,
      "height": 0,
      "position": null,
      "element_id": "HTn4ew51",
      "original_top": null,
      "original_left": null,
      "original_size": null,
      "original_transformation": null
    },
    "KqE4943S": {
      "hvml": null,
      "type": "scene",
      "position": null,
      "element_id": "KqE4943S",
      "original_top": null,
      "original_left": null,
      "original_size": null,
      "original_transformation": null
    },
    "NYoi9nt5": {
      "fps": null,
      "hvml": null,
      "name": "Elis in the library classroom",
      "type": "avatar",
      "width": 2752,
      "height": 1536,
      "kit_id": null,
      "face_id": null,
      "premium": null,
      "preview": {
        "normal": {
          "src": "https://files2.heygen.ai/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP?Expires=1790019941&Signature=i~JteEf-zIfO4goKnjapXqedSTkcp3NUCOauiqE0Cb5HOorc1yfYLOrDsDBA5BEbURei1PqmcZrFJoNWQJCXedhGSZjzn~lvxR5mp~2t7ab7GedIfcEGJoF3BWrIY~LIB2JFscgzG1dkw4nLcADF4FxmwEGdZQNx54GXtsxFTg~G3t-7i3Zxxbaa1v3u~-1aAI29UqSFhrwZgqiy2xUeh3grPjyZ4H3p3bekyuJ6w-iv6SZPImH3Fjj9R3bhVDGqATSlX-3CHLIMVcSLnRN9VP9qymMSZfuVzHlfVHjI636qIBdpQyz4Pbrc3~Z41cgQEmtdmHI1lEPqml7nvw08cw__&Key-Pair-Id=K38HBHX5LX3X2H",
          "size": {
            "width": 2752.0,
            "height": 1536.0
          }
        },
        "spotlight": null
      },
      "face_url": null,
      "faceswap": null,
      "gestures": null,
      "position": null,
      "crop_rect": {
        "circle": {
          "x": 477.8135986328125,
          "y": 281.70452880859375,
          "width": 654.9371337890625,
          "height": 654.9371337890625
        },
        "close_up": {
          "x": 145.283203125,
          "y": 199.9940185546875,
          "width": 1309.874267578125,
          "height": 1309.874267578125
        }
      },
      "enable_4k": false,
      "has_alpha": false,
      "is_motion": false,
      "outfit_id": null,
      "pose_name": "Elis in the library classroom",
      "element_id": "NYoi9nt5",
      "is_private": true,
      "avatar_name": "Elis in the library classroom",
      "avatar_type": "photo_avatar",
      "original_top": null,
      "natural_width": 2752,
      "original_left": null,
      "original_size": null,
      "webm_eligible": null,
      "enable_enhance": true,
      "enable_matting": true,
      "natural_height": 1536,
      "available_style": {
        "circle": true,
        "normal": true,
        "close_up": true
      },
      "avatar_state_id": "2d0d7a898328477d9f0e92a71fd840d0",
      "crop_box_crop_x": {
        "normal": 0.0,
        "close_up": 0.0
      },
      "blurred_lips_mp4": "",
      "avatar_group_name": "Elis",
      "blurred_lips_webm": "",
      "preview_image_url": "s3://heygen-product/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP",
      "preview_video_url": "",
      "support_avatar_iv": true,
      "enable_eye_contact": false,
      "is_avatar_iv_motion": false,
      "processed_image_url": "s3://heygen-product/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP",
      "enable_change_outfit": null,
      "spotlight_mode_width": null,
      "photo_avatar_metadata": {
        "photar_version": "V3"
      },
      "spotlight_mode_height": null,
      "is_incomplete_metadata": null,
      "original_transformation": null,
      "unlimited_mode_disabled": false,
      "spotlight_mode_crop_rect": null,
      "gesture_preprocessing_state": null,
      "unlimited_mode_disabled_reason": null
    },
    "QkCq0RZd": {
      "fps": null,
      "hvml": null,
      "name": "Elis in the library classroom",
      "type": "avatar",
      "width": 2752,
      "height": 1536,
      "kit_id": null,
      "face_id": null,
      "premium": null,
      "preview": {
        "normal": {
          "src": "https://files2.heygen.ai/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP?Expires=1790019941&Signature=i~JteEf-zIfO4goKnjapXqedSTkcp3NUCOauiqE0Cb5HOorc1yfYLOrDsDBA5BEbURei1PqmcZrFJoNWQJCXedhGSZjzn~lvxR5mp~2t7ab7GedIfcEGJoF3BWrIY~LIB2JFscgzG1dkw4nLcADF4FxmwEGdZQNx54GXtsxFTg~G3t-7i3Zxxbaa1v3u~-1aAI29UqSFhrwZgqiy2xUeh3grPjyZ4H3p3bekyuJ6w-iv6SZPImH3Fjj9R3bhVDGqATSlX-3CHLIMVcSLnRN9VP9qymMSZfuVzHlfVHjI636qIBdpQyz4Pbrc3~Z41cgQEmtdmHI1lEPqml7nvw08cw__&Key-Pair-Id=K38HBHX5LX3X2H",
          "size": {
            "width": 2752.0,
            "height": 1536.0
          }
        },
        "spotlight": null
      },
      "face_url": null,
      "faceswap": null,
      "gestures": null,
      "position": {
        "type": "center",
        "offset": {
          "x": 0.0,
          "y": 0.0
        }
      },
      "crop_rect": {
        "circle": {
          "x": 477.8135986328125,
          "y": 281.70452880859375,
          "width": 654.9371337890625,
          "height": 654.9371337890625
        },
        "close_up": {
          "x": 145.283203125,
          "y": 199.9940185546875,
          "width": 1309.874267578125,
          "height": 1309.874267578125
        }
      },
      "enable_4k": false,
      "has_alpha": false,
      "is_motion": false,
      "outfit_id": null,
      "pose_name": "Elis in the library classroom",
      "element_id": "QkCq0RZd",
      "is_private": true,
      "avatar_name": "Elis in the library classroom",
      "avatar_type": "photo_avatar",
      "original_top": null,
      "natural_width": 2752,
      "original_left": null,
      "original_size": null,
      "webm_eligible": null,
      "enable_enhance": true,
      "enable_matting": true,
      "natural_height": 1536,
      "available_style": {
        "circle": true,
        "normal": true,
        "close_up": true
      },
      "avatar_state_id": "2d0d7a898328477d9f0e92a71fd840d0",
      "crop_box_crop_x": {
        "normal": 0.0,
        "close_up": 0.0
      },
      "blurred_lips_mp4": "",
      "avatar_group_name": "Elis",
      "blurred_lips_webm": "",
      "preview_image_url": "s3://heygen-product/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP",
      "preview_video_url": "",
      "support_avatar_iv": true,
      "enable_eye_contact": false,
      "is_avatar_iv_motion": false,
      "processed_image_url": "s3://heygen-product/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP",
      "enable_change_outfit": null,
      "spotlight_mode_width": null,
      "photo_avatar_metadata": {
        "photar_version": "V3"
      },
      "spotlight_mode_height": null,
      "is_incomplete_metadata": null,
      "original_transformation": null,
      "unlimited_mode_disabled": false,
      "spotlight_mode_crop_rect": null,
      "gesture_preprocessing_state": null,
      "unlimited_mode_disabled_reason": null
    },
    "Rf6coP7k": {
      "hvml": null,
      "type": "scene",
      "position": null,
      "element_id": "Rf6coP7k",
      "original_top": null,
      "original_left": null,
      "original_size": null,
      "original_transformation": null
    },
    "WKnYo0d9": {
      "fps": null,
      "hvml": null,
      "name": "Elis in the library classroom",
      "type": "avatar",
      "width": 2752,
      "height": 1536,
      "kit_id": null,
      "face_id": null,
      "premium": null,
      "preview": {
        "normal": {
          "src": "https://files2.heygen.ai/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP?Expires=1790019941&Signature=i~JteEf-zIfO4goKnjapXqedSTkcp3NUCOauiqE0Cb5HOorc1yfYLOrDsDBA5BEbURei1PqmcZrFJoNWQJCXedhGSZjzn~lvxR5mp~2t7ab7GedIfcEGJoF3BWrIY~LIB2JFscgzG1dkw4nLcADF4FxmwEGdZQNx54GXtsxFTg~G3t-7i3Zxxbaa1v3u~-1aAI29UqSFhrwZgqiy2xUeh3grPjyZ4H3p3bekyuJ6w-iv6SZPImH3Fjj9R3bhVDGqATSlX-3CHLIMVcSLnRN9VP9qymMSZfuVzHlfVHjI636qIBdpQyz4Pbrc3~Z41cgQEmtdmHI1lEPqml7nvw08cw__&Key-Pair-Id=K38HBHX5LX3X2H",
          "size": {
            "width": 2752.0,
            "height": 1536.0
          }
        },
        "spotlight": null
      },
      "face_url": null,
      "faceswap": null,
      "gestures": null,
      "position": {
        "type": "center",
        "offset": {
          "x": 0.0,
          "y": 0.0
        }
      },
      "crop_rect": {
        "circle": {
          "x": 477.8135986328125,
          "y": 281.70452880859375,
          "width": 654.9371337890625,
          "height": 654.9371337890625
        },
        "close_up": {
          "x": 145.283203125,
          "y": 199.9940185546875,
          "width": 1309.874267578125,
          "height": 1309.874267578125
        }
      },
      "enable_4k": false,
      "has_alpha": false,
      "is_motion": false,
      "outfit_id": null,
      "pose_name": "Elis in the library classroom",
      "element_id": "WKnYo0d9",
      "is_private": true,
      "avatar_name": "Elis in the library classroom",
      "avatar_type": "photo_avatar",
      "original_top": null,
      "natural_width": 2752,
      "original_left": null,
      "original_size": null,
      "webm_eligible": null,
      "enable_enhance": true,
      "enable_matting": true,
      "natural_height": 1536,
      "available_style": {
        "circle": true,
        "normal": true,
        "close_up": true
      },
      "avatar_state_id": "2d0d7a898328477d9f0e92a71fd840d0",
      "crop_box_crop_x": {
        "normal": 0.0,
        "close_up": 0.0
      },
      "blurred_lips_mp4": "",
      "avatar_group_name": "Elis",
      "blurred_lips_webm": "",
      "preview_image_url": "s3://heygen-product/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP",
      "preview_video_url": "",
      "support_avatar_iv": true,
      "enable_eye_contact": false,
      "is_avatar_iv_motion": false,
      "processed_image_url": "s3://heygen-product/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP",
      "enable_change_outfit": null,
      "spotlight_mode_width": null,
      "photo_avatar_metadata": {
        "photar_version": "V3"
      },
      "spotlight_mode_height": null,
      "is_incomplete_metadata": null,
      "original_transformation": null,
      "unlimited_mode_disabled": false,
      "spotlight_mode_crop_rect": null,
      "gesture_preprocessing_state": null,
      "unlimited_mode_disabled_reason": null
    },
    "X7WZfDph": {
      "hvml": null,
      "type": "scene",
      "position": null,
      "element_id": "X7WZfDph",
      "original_top": null,
      "original_left": null,
      "original_size": null,
      "original_transformation": null
    },
    "XxU9GdYk": {
      "url": "s3://heygen-resources-prod/text_to_speech/7097eee25a5f40ea8e0b4bc549fefaa0/m2oepJCLyzU9OTVL2zev/id=49120ce3-ed22-40a1-8d92-e82099d19aac.wav",
      "hvml": null,
      "seed": null,
      "type": "tts",
      "error": null,
      "words": [
        {
          "word": "<start>",
          "end_time": 0.0,
          "start_time": 0.0
        },
        {
          "word": "Olá,",
          "end_time": 0.68,
          "start_time": 0.359
        },
        {
          "word": "eu",
          "end_time": 1.399,
          "start_time": 1.299
        },
        {
          "word": "me",
          "end_time": 1.579,
          "start_time": 1.419
        },
        {
          "word": "chamo",
          "end_time": 1.819,
          "start_time": 1.599
        },
        {
          "word": "Vanessa",
          "end_time": 2.519,
          "start_time": 1.919
        },
        {
          "word": "e",
          "end_time": 2.98,
          "start_time": 2.939
        },
        {
          "word": "estou",
          "end_time": 3.339,
          "start_time": 3.0
        },
        {
          "word": "aqui",
          "end_time": 3.72,
          "start_time": 3.359
        },
        {
          "word": "para",
          "end_time": 3.979,
          "start_time": 3.759
        },
        {
          "word": "conduzir",
          "end_time": 4.539,
          "start_time": 4.0
        },
        {
          "word": "você,",
          "end_time": 5.339,
          "start_time": 4.639
        },
        {
          "word": "em",
          "end_time": 5.519,
          "start_time": 5.4
        },
        {
          "word": "uma",
          "end_time": 5.679,
          "start_time": 5.539
        },
        {
          "word": "trilha",
          "end_time": 6.279,
          "start_time": 5.879
        },
        {
          "word": "de",
          "end_time": 6.42,
          "start_time": 6.319
        },
        {
          "word": "conhecimento,",
          "end_time": 7.639,
          "start_time": 6.46
        },
        {
          "word": "sobre",
          "end_time": 7.899,
          "start_time": 7.699
        },
        {
          "word": "o",
          "end_time": 8.0,
          "start_time": 7.919
        },
        {
          "word": "sistema",
          "end_time": 8.56,
          "start_time": 8.039
        },
        {
          "word": "de",
          "end_time": 8.679,
          "start_time": 8.619
        },
        {
          "word": "gestão",
          "end_time": 9.32,
          "start_time": 8.76
        },
        {
          "word": "de",
          "end_time": 9.519,
          "start_time": 9.34
        },
        {
          "word": "crises",
          "end_time": 10.099,
          "start_time": 9.579
        },
        {
          "word": "reputacionais.",
          "end_time": 11.219,
          "start_time": 10.139
        },
        {
          "word": "<break time=\"0.5s\"/>",
          "end_time": 11.719,
          "start_time": 11.219
        },
        {
          "word": "<end>",
          "end_time": 12.168004535147393,
          "start_time": 12.168004535147393
        }
      ],
      "duration": 12.168004535147393,
      "voice_id": "m2oepJCLyzU9OTVL2zev",
      "element_id": "XxU9GdYk",
      "request_id": null,
      "auto_engine": null,
      "used_engine": "mockingbird",
      "audio_duration": null,
      "item_needs_tts": false,
      "next_request_ids": [],
      "next_request_text": null,
      "previous_request_ids": [],
      "previous_request_text": null,
      "caption_override_words": null,
      "next_request_audio_url": null,
      "is_generated_in_workflow": true,
      "previous_request_audio_url": null
    },
    "YvHFKVQC": {
      "url": "s3://heygen-resources-prod/text_to_speech/7097eee25a5f40ea8e0b4bc549fefaa0/m2oepJCLyzU9OTVL2zev/id=ad3d1a6f-ff44-400f-9de1-6dbff8011d76.wav",
      "hvml": null,
      "seed": null,
      "type": "tts",
      "error": null,
      "words": [
        {
          "word": "<start>",
          "end_time": 0.0,
          "start_time": 0.0
        },
        {
          "word": "Nesta",
          "end_time": 0.74,
          "start_time": 0.399
        },
        {
          "word": "situação,",
          "end_time": 1.479,
          "start_time": 0.819
        },
        {
          "word": "o",
          "end_time": 1.979,
          "start_time": 1.899
        },
        {
          "word": "que",
          "end_time": 2.099,
          "start_time": 2.019
        },
        {
          "word": "você",
          "end_time": 2.379,
          "start_time": 2.159
        },
        {
          "word": "faz",
          "end_time": 2.679,
          "start_time": 2.46
        },
        {
          "word": "primeiro?",
          "end_time": 3.179,
          "start_time": 2.72
        },
        {
          "word": "Letra",
          "end_time": 4.42,
          "start_time": 4.119
        },
        {
          "word": "A:",
          "end_time": 4.719,
          "start_time": 4.559
        },
        {
          "word": "Mantém",
          "end_time": 6.059,
          "start_time": 5.599
        },
        {
          "word": "a",
          "end_time": 6.139,
          "start_time": 6.099
        },
        {
          "word": "atividade",
          "end_time": 6.96,
          "start_time": 6.199
        },
        {
          "word": "para",
          "end_time": 7.399,
          "start_time": 7.259
        },
        {
          "word": "não",
          "end_time": 7.559,
          "start_time": 7.46
        },
        {
          "word": "dar",
          "end_time": 7.779,
          "start_time": 7.639
        },
        {
          "word": "visibilidade",
          "end_time": 8.659,
          "start_time": 7.859
        },
        {
          "word": "ao",
          "end_time": 8.76,
          "start_time": 8.699
        },
        {
          "word": "episódio",
          "end_time": 9.5,
          "start_time": 8.899
        },
        {
          "word": "e",
          "end_time": 10.0,
          "start_time": 9.92
        },
        {
          "word": "conversa",
          "end_time": 10.639,
          "start_time": 10.059
        },
        {
          "word": "com",
          "end_time": 10.78,
          "start_time": 10.699
        },
        {
          "word": "a",
          "end_time": 10.859,
          "start_time": 10.819
        },
        {
          "word": "turma",
          "end_time": 11.399,
          "start_time": 11.0
        },
        {
          "word": "outro",
          "end_time": 11.759,
          "start_time": 11.439
        },
        {
          "word": "dia.",
          "end_time": 12.119,
          "start_time": 11.899
        },
        {
          "word": "Letra",
          "end_time": 13.619,
          "start_time": 13.34
        },
        {
          "word": "B:",
          "end_time": 13.899,
          "start_time": 13.759
        },
        {
          "word": "Interrompe",
          "end_time": 15.439,
          "start_time": 14.779
        },
        {
          "word": "a",
          "end_time": 15.52,
          "start_time": 15.5
        },
        {
          "word": "conduta,",
          "end_time": 16.119,
          "start_time": 15.599
        },
        {
          "word": "protege",
          "end_time": 17.179,
          "start_time": 16.6
        },
        {
          "word": "o",
          "end_time": 17.239,
          "start_time": 17.219
        },
        {
          "word": "estudante",
          "end_time": 17.879,
          "start_time": 17.34
        },
        {
          "word": "de",
          "end_time": 18.079,
          "start_time": 17.959
        },
        {
          "word": "nova",
          "end_time": 18.379,
          "start_time": 18.139
        },
        {
          "word": "exposição,",
          "end_time": 19.159,
          "start_time": 18.5
        },
        {
          "word": "estabelece",
          "end_time": 20.459,
          "start_time": 19.779
        },
        {
          "word": "o",
          "end_time": 20.52,
          "start_time": 20.5
        },
        {
          "word": "limite",
          "end_time": 21.02,
          "start_time": 20.6
        },
        {
          "word": "de",
          "end_time": 21.199,
          "start_time": 21.1
        },
        {
          "word": "forma",
          "end_time": 21.52,
          "start_time": 21.26
        },
        {
          "word": "firme",
          "end_time": 22.139,
          "start_time": 21.76
        },
        {
          "word": "e",
          "end_time": 22.219,
          "start_time": 22.199
        },
        {
          "word": "serena",
          "end_time": 22.76,
          "start_time": 22.359
        },
        {
          "word": "e",
          "end_time": 23.319,
          "start_time": 23.299
        },
        {
          "word": "informa",
          "end_time": 23.92,
          "start_time": 23.359
        },
        {
          "word": "que",
          "end_time": 24.059,
          "start_time": 24.019
        },
        {
          "word": "fará",
          "end_time": 24.42,
          "start_time": 24.199
        },
        {
          "word": "os",
          "end_time": 24.579,
          "start_time": 24.5
        },
        {
          "word": "encaminhamentos",
          "end_time": 25.399,
          "start_time": 24.619
        },
        {
          "word": "previstos.",
          "end_time": 26.099,
          "start_time": 25.479
        },
        {
          "word": "Ou",
          "end_time": 27.239,
          "start_time": 27.18
        },
        {
          "word": "Letra",
          "end_time": 27.599,
          "start_time": 27.319
        },
        {
          "word": "C:",
          "end_time": 27.879,
          "start_time": 27.84
        },
        {
          "word": "Pede",
          "end_time": 29.059,
          "start_time": 28.779
        },
        {
          "word": "que",
          "end_time": 29.199,
          "start_time": 29.139
        },
        {
          "word": "os",
          "end_time": 29.34,
          "start_time": 29.239
        },
        {
          "word": "próprios",
          "end_time": 29.859,
          "start_time": 29.459
        },
        {
          "word": "estudantes",
          "end_time": 30.559,
          "start_time": 29.959
        },
        {
          "word": "resolvam",
          "end_time": 31.179,
          "start_time": 30.619
        },
        {
          "word": "o",
          "end_time": 31.279,
          "start_time": 31.219
        },
        {
          "word": "conflito,",
          "end_time": 31.86,
          "start_time": 31.34
        },
        {
          "word": "pois",
          "end_time": 32.459,
          "start_time": 32.299
        },
        {
          "word": "desenvolver",
          "end_time": 33.18,
          "start_time": 32.52
        },
        {
          "word": "autonomia",
          "end_time": 33.84,
          "start_time": 33.239
        },
        {
          "word": "também",
          "end_time": 34.34,
          "start_time": 33.979
        },
        {
          "word": "faz",
          "end_time": 34.7,
          "start_time": 34.459
        },
        {
          "word": "parte",
          "end_time": 35.0,
          "start_time": 34.719
        },
        {
          "word": "da",
          "end_time": 35.099,
          "start_time": 35.059
        },
        {
          "word": "aprendizagem.",
          "end_time": 35.899,
          "start_time": 35.2
        },
        {
          "word": "<break time=\"0.5s\"/>",
          "end_time": 36.399,
          "start_time": 35.899
        },
        {
          "word": "<end>",
          "end_time": 36.888004535147395,
          "start_time": 36.888004535147395
        }
      ],
      "duration": 36.888004535147395,
      "voice_id": "m2oepJCLyzU9OTVL2zev",
      "element_id": "YvHFKVQC",
      "request_id": null,
      "auto_engine": null,
      "used_engine": null,
      "audio_duration": null,
      "item_needs_tts": false,
      "next_request_ids": [],
      "next_request_text": null,
      "previous_request_ids": [],
      "previous_request_text": null,
      "caption_override_words": null,
      "next_request_audio_url": null,
      "is_generated_in_workflow": true,
      "previous_request_audio_url": null
    },
    "blqvIoz7": {
      "fps": null,
      "hvml": null,
      "name": "Elis in the library classroom",
      "type": "avatar",
      "width": 2752,
      "height": 1536,
      "kit_id": null,
      "face_id": null,
      "premium": null,
      "preview": {
        "normal": {
          "src": "https://files2.heygen.ai/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP?Expires=1790019941&Signature=i~JteEf-zIfO4goKnjapXqedSTkcp3NUCOauiqE0Cb5HOorc1yfYLOrDsDBA5BEbURei1PqmcZrFJoNWQJCXedhGSZjzn~lvxR5mp~2t7ab7GedIfcEGJoF3BWrIY~LIB2JFscgzG1dkw4nLcADF4FxmwEGdZQNx54GXtsxFTg~G3t-7i3Zxxbaa1v3u~-1aAI29UqSFhrwZgqiy2xUeh3grPjyZ4H3p3bekyuJ6w-iv6SZPImH3Fjj9R3bhVDGqATSlX-3CHLIMVcSLnRN9VP9qymMSZfuVzHlfVHjI636qIBdpQyz4Pbrc3~Z41cgQEmtdmHI1lEPqml7nvw08cw__&Key-Pair-Id=K38HBHX5LX3X2H",
          "size": {
            "width": 2752.0,
            "height": 1536.0
          }
        },
        "spotlight": null
      },
      "face_url": null,
      "faceswap": null,
      "gestures": null,
      "position": null,
      "crop_rect": {
        "circle": {
          "x": 477.8135986328125,
          "y": 281.70452880859375,
          "width": 654.9371337890625,
          "height": 654.9371337890625
        },
        "close_up": {
          "x": 145.283203125,
          "y": 199.9940185546875,
          "width": 1309.874267578125,
          "height": 1309.874267578125
        }
      },
      "enable_4k": false,
      "has_alpha": false,
      "is_motion": false,
      "outfit_id": null,
      "pose_name": "Elis in the library classroom",
      "element_id": "blqvIoz7",
      "is_private": true,
      "avatar_name": "Elis in the library classroom",
      "avatar_type": "photo_avatar",
      "original_top": null,
      "natural_width": 2752,
      "original_left": null,
      "original_size": null,
      "webm_eligible": null,
      "enable_enhance": true,
      "enable_matting": true,
      "natural_height": 1536,
      "available_style": {
        "circle": true,
        "normal": true,
        "close_up": true
      },
      "avatar_state_id": "2d0d7a898328477d9f0e92a71fd840d0",
      "crop_box_crop_x": {
        "normal": 0.0,
        "close_up": 0.0
      },
      "blurred_lips_mp4": "",
      "avatar_group_name": "Elis",
      "blurred_lips_webm": "",
      "preview_image_url": "s3://heygen-product/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP",
      "preview_video_url": "",
      "support_avatar_iv": true,
      "enable_eye_contact": false,
      "is_avatar_iv_motion": false,
      "processed_image_url": "s3://heygen-product/talking_photo/2d0d7a898328477d9f0e92a71fd840d0/3228225792ae41d88fef7b0fed110da3.WEBP",
      "enable_change_outfit": null,
      "spotlight_mode_width": null,
      "photo_avatar_metadata": {
        "photar_version": "V3"
      },
      "spotlight_mode_height": null,
      "is_incomplete_metadata": null,
      "original_transformation": null,
      "unlimited_mode_disabled": false,
      "spotlight_mode_crop_rect": null,
      "gesture_preprocessing_state": null,
      "unlimited_mode_disabled_reason": null
    },
    "eA4fQhYp": {
      "hvml": null,
      "type": "scene",
      "position": null,
      "element_id": "eA4fQhYp",
      "original_top": null,
      "original_left": null,
      "original_size": null,
      "original_transformation": null
    },
    "iOOYv8s5": {
      "hvml": null,
      "type": "scene",
      "position": null,
      "element_id": "iOOYv8s5",
      "original_top": null,
      "original_left": null,
      "original_size": null,
      "original_transformation": null
    },
    "mnTUDS4M": {
      "url": "s3://heygen-resources-prod/text_to_speech/7097eee25a5f40ea8e0b4bc549fefaa0/m2oepJCLyzU9OTVL2zev/id=69f463f7-03bc-43b0-9cc6-e523f2439114.wav",
      "hvml": null,
      "seed": null,
      "type": "tts",
      "error": null,
      "words": [
        {
          "word": "<start>",
          "end_time": 0.0,
          "start_time": 0.0
        },
        {
          "word": "<break time=\"0.5s\"/>",
          "end_time": 0.5,
          "start_time": 0.0
        },
        {
          "word": "Agir",
          "end_time": 1.219,
          "start_time": 0.859
        },
        {
          "word": "cedo",
          "end_time": 1.759,
          "start_time": 1.379
        },
        {
          "word": "contém",
          "end_time": 2.539,
          "start_time": 1.98
        },
        {
          "word": "o",
          "end_time": 2.68,
          "start_time": 2.559
        },
        {
          "word": "dano",
          "end_time": 3.079,
          "start_time": 2.74
        },
        {
          "word": "sem",
          "end_time": 3.5,
          "start_time": 3.279
        },
        {
          "word": "transformar",
          "end_time": 4.159,
          "start_time": 3.539
        },
        {
          "word": "a",
          "end_time": 4.259,
          "start_time": 4.24
        },
        {
          "word": "sala",
          "end_time": 4.679,
          "start_time": 4.399
        },
        {
          "word": "em",
          "end_time": 4.86,
          "start_time": 4.739
        },
        {
          "word": "tribunal.",
          "end_time": 5.4,
          "start_time": 4.9
        },
        {
          "word": "A",
          "end_time": 6.339,
          "start_time": 6.319
        },
        {
          "word": "intervenção",
          "end_time": 7.119,
          "start_time": 6.4
        },
        {
          "word": "deve",
          "end_time": 7.42,
          "start_time": 7.179
        },
        {
          "word": "cessar",
          "end_time": 7.96,
          "start_time": 7.48
        },
        {
          "word": "a",
          "end_time": 8.059000000000001,
          "start_time": 7.98
        },
        {
          "word": "conduta,",
          "end_time": 8.659,
          "start_time": 8.119
        },
        {
          "word": "proteger",
          "end_time": 9.699,
          "start_time": 9.059
        },
        {
          "word": "quem",
          "end_time": 9.96,
          "start_time": 9.8
        },
        {
          "word": "foi",
          "end_time": 10.159,
          "start_time": 10.019
        },
        {
          "word": "atingido",
          "end_time": 10.82,
          "start_time": 10.199
        },
        {
          "word": "e",
          "end_time": 11.279,
          "start_time": 11.219
        },
        {
          "word": "abrir",
          "end_time": 11.739,
          "start_time": 11.359
        },
        {
          "word": "o",
          "end_time": 11.859,
          "start_time": 11.779
        },
        {
          "word": "caminho",
          "end_time": 12.399,
          "start_time": 11.92
        },
        {
          "word": "para",
          "end_time": 12.619,
          "start_time": 12.46
        },
        {
          "word": "a",
          "end_time": 12.659,
          "start_time": 12.639
        },
        {
          "word": "Convivência",
          "end_time": 13.48,
          "start_time": 12.779
        },
        {
          "word": "Ética",
          "end_time": 14.199,
          "start_time": 13.679
        },
        {
          "word": "e",
          "end_time": 14.319,
          "start_time": 14.259
        },
        {
          "word": "a",
          "end_time": 14.399,
          "start_time": 14.38
        },
        {
          "word": "lideranç",
          "end_time": 15.159,
          "start_time": 14.519
        },
        {
          "word": "a.",
          "end_time": 16.198999999999998,
          "start_time": 16.179000000000002
        },
        {
          "word": "Ignorar",
          "end_time": 16.979,
          "start_time": 16.279
        },
        {
          "word": "ou",
          "end_time": 17.18,
          "start_time": 17.039
        },
        {
          "word": "transferir",
          "end_time": 17.799,
          "start_time": 17.239
        },
        {
          "word": "integralmente",
          "end_time": 18.699,
          "start_time": 17.819
        },
        {
          "word": "a",
          "end_time": 18.84,
          "start_time": 18.76
        },
        {
          "word": "solução",
          "end_time": 19.34,
          "start_time": 18.899
        },
        {
          "word": "aos",
          "end_time": 19.54,
          "start_time": 19.379
        },
        {
          "word": "estudantes",
          "end_time": 20.299,
          "start_time": 19.579
        },
        {
          "word": "pode",
          "end_time": 20.899,
          "start_time": 20.659
        },
        {
          "word": "ampliar",
          "end_time": 21.559,
          "start_time": 20.959
        },
        {
          "word": "a",
          "end_time": 21.62,
          "start_time": 21.6
        },
        {
          "word": "vulnerabilidade.",
          "end_time": 22.859,
          "start_time": 21.699
        },
        {
          "word": "<break time=\"0.5s\"/>",
          "end_time": 23.359,
          "start_time": 22.859
        },
        {
          "word": "<end>",
          "end_time": 24.744013605442177,
          "start_time": 24.744013605442177
        }
      ],
      "duration": 24.744013605442177,
      "voice_id": "m2oepJCLyzU9OTVL2zev",
      "element_id": "mnTUDS4M",
      "request_id": null,
      "auto_engine": null,
      "used_engine": null,
      "audio_duration": null,
      "item_needs_tts": false,
      "next_request_ids": [],
      "next_request_text": null,
      "previous_request_ids": [],
      "previous_request_text": null,
      "caption_override_words": null,
      "next_request_audio_url": null,
      "is_generated_in_workflow": true,
      "previous_request_audio_url": null
    },
    "oCwemNJp": {
      "hvml": null,
      "type": "scene",
      "position": null,
      "element_id": "oCwemNJp",
      "original_top": null,
      "original_left": null,
      "original_size": null,
      "original_transformation": null
    },
    "rXmEkoGY": {
      "url": "s3://heygen-resources-prod/text_to_speech/7097eee25a5f40ea8e0b4bc549fefaa0/m2oepJCLyzU9OTVL2zev/id=4c41548e-0569-41dc-a81a-50b7ffa26143.wav",
      "hvml": null,
      "seed": null,
      "type": "tts",
      "error": null,
      "words": [
        {
          "word": "<start>",
          "end_time": 0.0,
          "start_time": 0.0
        },
        {
          "word": "<break time=\"0.5s\"/>",
          "end_time": 0.5,
          "start_time": 0.0
        },
        {
          "word": "Imagine",
          "end_time": 1.459,
          "start_time": 0.859
        },
        {
          "word": "que",
          "end_time": 1.6,
          "start_time": 1.5
        },
        {
          "word": "você",
          "end_time": 1.86,
          "start_time": 1.639
        },
        {
          "word": "está",
          "end_time": 2.199,
          "start_time": 1.959
        },
        {
          "word": "conduzindo",
          "end_time": 2.94,
          "start_time": 2.2190000000000003
        },
        {
          "word": "uma",
          "end_time": 3.139,
          "start_time": 2.96
        },
        {
          "word": "atividade.",
          "end_time": 4.0,
          "start_time": 3.179
        },
        {
          "word": "Em",
          "end_time": 4.92,
          "start_time": 4.679
        },
        {
          "word": "poucos",
          "end_time": 5.339,
          "start_time": 4.96
        },
        {
          "word": "segundos,",
          "end_time": 6.039,
          "start_time": 5.38
        },
        {
          "word": "uma",
          "end_time": 6.46,
          "start_time": 6.319
        },
        {
          "word": "brincadeira",
          "end_time": 7.359,
          "start_time": 6.559
        },
        {
          "word": "deixa",
          "end_time": 7.839,
          "start_time": 7.42
        },
        {
          "word": "de",
          "end_time": 8.019,
          "start_time": 7.859
        },
        {
          "word": "ser",
          "end_time": 8.219000000000001,
          "start_time": 8.099
        },
        {
          "word": "brincadeira",
          "end_time": 9.0,
          "start_time": 8.299
        },
        {
          "word": "para",
          "end_time": 9.18,
          "start_time": 9.019
        },
        {
          "word": "alguém.",
          "end_time": 9.559,
          "start_time": 9.22
        },
        {
          "word": "Há",
          "end_time": 10.479,
          "start_time": 10.42
        },
        {
          "word": "constrangimento,",
          "end_time": 11.639,
          "start_time": 10.579
        },
        {
          "word": "um",
          "end_time": 12.099,
          "start_time": 12.039
        },
        {
          "word": "celular",
          "end_time": 12.639,
          "start_time": 12.199
        },
        {
          "word": "gravando",
          "end_time": 13.599,
          "start_time": 12.699
        },
        {
          "word": "e",
          "end_time": 13.699,
          "start_time": 13.659
        },
        {
          "word": "uma",
          "end_time": 13.88,
          "start_time": 13.779
        },
        {
          "word": "turma",
          "end_time": 14.399,
          "start_time": 14.059
        },
        {
          "word": "observando.",
          "end_time": 15.259,
          "start_time": 14.519
        },
        {
          "word": "<break time=\"0.5s\"/>",
          "end_time": 15.759,
          "start_time": 15.259
        },
        {
          "word": "<end>",
          "end_time": 16.224013605442178,
          "start_time": 16.224013605442178
        }
      ],
      "duration": 16.224013605442178,
      "voice_id": "m2oepJCLyzU9OTVL2zev",
      "element_id": "rXmEkoGY",
      "request_id": null,
      "auto_engine": null,
      "used_engine": null,
      "audio_duration": null,
      "item_needs_tts": false,
      "next_request_ids": [],
      "next_request_text": null,
      "previous_request_ids": [],
      "previous_request_text": null,
      "caption_override_words": null,
      "next_request_audio_url": null,
      "is_generated_in_workflow": true,
      "previous_request_audio_url": null
    },
    "yAgebs2q": {
      "url": "s3://heygen-resources-prod/text_to_speech/7097eee25a5f40ea8e0b4bc549fefaa0/m2oepJCLyzU9OTVL2zev/id=518bce79-561a-42ce-a650-8570b6faa9ce.wav",
      "hvml": null,
      "seed": null,
      "type": "tts",
      "error": null,
      "words": [
        {
          "word": "<start>",
          "end_time": 0.0,
          "start_time": 0.0
        },
        {
          "word": "<break time=\"5.0s\"/>",
          "end_time": 5.0,
          "start_time": 0.0
        },
        {
          "word": "<end>",
          "end_time": 30.08,
          "start_time": 5.0
        }
      ],
      "duration": 30.08,
      "voice_id": "m2oepJCLyzU9OTVL2zev",
      "element_id": "yAgebs2q",
      "request_id": null,
      "auto_engine": null,
      "used_engine": "mockingbird",
      "audio_duration": 5.0,
      "item_needs_tts": false,
      "next_request_ids": [],
      "next_request_text": null,
      "previous_request_ids": [],
      "previous_request_text": null,
      "caption_override_words": null,
      "next_request_audio_url": null,
      "is_generated_in_workflow": true,
      "previous_request_audio_url": null
    },
    "heygen-66286d310c9e494c8453e17c9b1429c2-0VkDxF0O": {
      "url": "s3://heygen-product/prod/movio/preset/audio/heygen_music/66286d310c9e494c8453e17c9b1429c2.wav",
      "hvml": null,
      "name": "Soft inspiring background music, low volume, emotional and direct",
      "seed": null,
      "text": null,
      "type": "audio",
      "words": [],
      "duration": 72.0,
      "fileType": null,
      "language": null,
      "element_id": "heygen-66286d310c9e494c8453e17c9b1429c2-0VkDxF0O",
      "asset_source": "heygen",
      "audio_duration": null,
      "source_audio_url": null,
      "transcribed_from_url": null,
      "caption_override_words": null,
      "is_generated_in_workflow": false
    }
  },
  "text_draft": {
    "script": {
      "elements": {
        "2MedGmgD": {
          "id": "2MedGmgD",
          "text": "Vamos à primeira missão: Prevenir.\nNa sala de aula, o cuidado começa antes. Assista ao vídeo a seguir.  <break time='0.5s'/> ",
          "type": "tts",
          "attributes": {
            "voice_id": "m2oepJCLyzU9OTVL2zev",
            "trim_to_speech": null,
            "voice_settings": {
              "model": null,
              "pitch": 0.0,
              "speed": 0.9,
              "style": null,
              "locale": "pt-BR",
              "volume": 1.0,
              "emotion": null,
              "stability": 0.5,
              "request_id": null,
              "similarity": null,
              "tts_settings": null,
              "reverb_location": null,
              "next_request_ids": null,
              "next_request_text": null,
              "use_speaker_boost": false,
              "previous_request_ids": null,
              "previous_request_text": null,
              "voice_engine_settings": {
                "seed": 997278578,
                "engine_type": "mockingbird"
              },
              "next_request_audio_url": null,
              "previous_request_audio_url": null
            }
          }
        },
        "XxU9GdYk": {
          "id": "XxU9GdYk",
          "text": "Olá, eu me chamo Vanessa e estou aqui para conduzir você, em uma trilha de conhecimento, sobre o sistema de gestão de crises reputacionais. <break time='0.5s'/> ",
          "type": "tts",
          "attributes": {
            "voice_id": "m2oepJCLyzU9OTVL2zev",
            "trim_to_speech": null,
            "voice_settings": {
              "model": null,
              "pitch": 0.0,
              "speed": 0.9,
              "style": null,
              "locale": "pt-BR",
              "volume": 1.0,
              "emotion": null,
              "stability": 0.5,
              "request_id": null,
              "similarity": null,
              "tts_settings": null,
              "reverb_location": null,
              "next_request_ids": null,
              "next_request_text": null,
              "use_speaker_boost": false,
              "previous_request_ids": null,
              "previous_request_text": null,
              "voice_engine_settings": {
                "seed": null,
                "engine_type": "mockingbird"
              },
              "next_request_audio_url": null,
              "previous_request_audio_url": null
            }
          }
        },
        "YvHFKVQC": {
          "id": "YvHFKVQC",
          "text": "Nesta situação, o que você faz primeiro?\nLetra A: Mantém a atividade para não dar visibilidade ao episódio e conversa com a turma outro dia.\nLetra B: Interrompe a conduta, protege o estudante de nova exposição, estabelece o limite de forma firme e serena e informa que fará os encaminhamentos previstos.\nOu Letra C: Pede que os próprios estudantes resolvam o conflito, pois desenvolver autonomia também faz parte da aprendizagem.\n <break time='0.5s'/> ",
          "type": "tts",
          "attributes": {
            "voice_id": "m2oepJCLyzU9OTVL2zev",
            "trim_to_speech": null,
            "voice_settings": {
              "model": null,
              "pitch": 0.0,
              "speed": 0.9,
              "style": null,
              "locale": "pt-BR",
              "volume": 1.0,
              "emotion": null,
              "stability": 0.5,
              "request_id": null,
              "similarity": null,
              "tts_settings": null,
              "reverb_location": null,
              "next_request_ids": null,
              "next_request_text": null,
              "use_speaker_boost": false,
              "previous_request_ids": null,
              "previous_request_text": null,
              "voice_engine_settings": {
                "seed": 997278578,
                "engine_type": "mockingbird"
              },
              "next_request_audio_url": null,
              "previous_request_audio_url": null
            }
          }
        },
        "mnTUDS4M": {
          "id": "mnTUDS4M",
          "text": " <break time='0.5s'/> Agir cedo contém o dano sem transformar a sala em tribunal. A intervenção deve cessar a conduta, proteger quem foi atingido e abrir o caminho para a Convivência Ética e a\nliderança. Ignorar ou transferir integralmente a solução aos estudantes pode ampliar a\nvulnerabilidade. <break time='0.5s'/> ",
          "type": "tts",
          "attributes": {
            "voice_id": "m2oepJCLyzU9OTVL2zev",
            "trim_to_speech": null,
            "voice_settings": {
              "model": null,
              "pitch": 0.0,
              "speed": 0.9,
              "style": null,
              "locale": "pt-BR",
              "volume": 1.0,
              "emotion": null,
              "stability": 0.5,
              "request_id": null,
              "similarity": null,
              "tts_settings": null,
              "reverb_location": null,
              "next_request_ids": null,
              "next_request_text": null,
              "use_speaker_boost": false,
              "previous_request_ids": null,
              "previous_request_text": null,
              "voice_engine_settings": {
                "seed": 997278578,
                "engine_type": "mockingbird"
              },
              "next_request_audio_url": null,
              "previous_request_audio_url": null
            }
          }
        },
        "rXmEkoGY": {
          "id": "rXmEkoGY",
          "text": " <break time='0.5s'/> Imagine que você está conduzindo uma atividade. Em poucos segundos, uma brincadeira deixa de ser brincadeira para alguém. Há constrangimento, um celular gravando e uma turma observando. <break time='0.5s'/>",
          "type": "tts",
          "attributes": {
            "voice_id": "m2oepJCLyzU9OTVL2zev",
            "trim_to_speech": null,
            "voice_settings": {
              "model": null,
              "pitch": 0.0,
              "speed": 0.9,
              "style": null,
              "locale": "pt-BR",
              "volume": 1.0,
              "emotion": null,
              "stability": 0.5,
              "request_id": null,
              "similarity": null,
              "tts_settings": null,
              "reverb_location": null,
              "next_request_ids": null,
              "next_request_text": null,
              "use_speaker_boost": false,
              "previous_request_ids": null,
              "previous_request_text": null,
              "voice_engine_settings": {
                "seed": 997278578,
                "engine_type": "mockingbird"
              },
              "next_request_audio_url": null,
              "previous_request_audio_url": null
            }
          }
        },
        "yAgebs2q": {
          "id": "yAgebs2q",
          "text": " <break time='5s'/> ",
          "type": "tts",
          "attributes": {
            "voice_id": "m2oepJCLyzU9OTVL2zev",
            "trim_to_speech": null,
            "voice_settings": {
              "model": null,
              "pitch": 0.0,
              "speed": 1.0,
              "style": null,
              "locale": "pt-BR",
              "volume": 1.0,
              "emotion": null,
              "stability": 0.5,
              "request_id": null,
              "similarity": null,
              "tts_settings": null,
              "reverb_location": null,
              "next_request_ids": null,
              "next_request_text": null,
              "use_speaker_boost": false,
              "previous_request_ids": null,
              "previous_request_text": null,
              "voice_engine_settings": {
                "seed": 997278578,
                "engine_type": "mockingbird"
              },
              "next_request_audio_url": null,
              "previous_request_audio_url": null
            }
          }
        }
      },
      "timeline": [
        "XxU9GdYk",
        "2MedGmgD",
        "yAgebs2q",
        "rXmEkoGY",
        "YvHFKVQC",
        "mnTUDS4M"
      ],
      "brand_kit_id": "093c8bb090824fd5b5c7531b37c36bb5",
      "brand_voice_id": "80d8135e219e40479624deabc928687c",
      "presenter_style": null,
      "sentence_level_tts": null,
      "brand_voice_enabled": true,
      "presenter_style_by_element": null
    },
    "visual": {
      "layout": [
        "KqE4943S",
        "iOOYv8s5",
        "Rf6coP7k",
        "oCwemNJp",
        "X7WZfDph",
        "eA4fQhYp"
      ],
      "elements": {
        "3uh8ldCz": {
          "id": "3uh8ldCz",
          "type": "avatar",
          "assets": null,
          "parent": null,
          "content": {
            "alpha": null,
            "model": "tokyo_v2_1_dmd_rlhf",
            "engine": "avatar_v",
            "prompt": null,
            "matting": false,
            "avatar_id": "2d0d7a898328477d9f0e92a71fd840d0",
            "resolution": "1080p",
            "gesture_mp4": null,
            "render_type": "normal",
            "frame_offset": null,
            "gesture_webm": null,
            "inference_mp4": null,
            "talking_photo": {
              "crop": null,
              "emotion": null,
              "enhance": false,
              "expression": null
            },
            "inference_webm": null,
            "render_type_v2": "normal",
            "avatar_group_id": "ea087fe9606344c5bd3c86ec091672b0",
            "engine_settings": {
              "model": "tokyo_v2_2",
              "resolution": "1080p",
              "engine_type": "cross_ref",
              "cross_ref_avatar_id": null
            },
            "inference_job_id": null,
            "avatar_background": null,
            "circle_background": "#f6f6fc",
            "avatar_artifact_id": null,
            "use_unlimited_mode": null,
            "cross_ref_avatar_id": null,
            "spotlight_image_url": null,
            "use_avatar_iv_model": true,
            "inference_packed_mp4": null,
            "keep_original_prompt": null,
            "spotlight_mode_width": null,
            "enable_spotlight_mode": null,
            "spotlight_mode_height": null,
            "use_third_party_model": null,
            "third_party_motion_type": null,
            "third_party_model_prompt": null,
            "avatar_iv_more_expressive": true,
            "enforce_legacy_talking_photo_inference": null
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": {
                "top": 0.0,
                "left": 0.0,
                "right": 0.0,
                "bottom": 0.0
              },
              "scale": {
                "x": 0.703125,
                "y": 0.703125
              }
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": {
              "rotate": {
                "angle": 0.0
              }
            },
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": null
        },
        "6SVkeGR7": {
          "id": "6SVkeGR7",
          "type": "video",
          "assets": {
            "video": "user_upload-3ff8f7f47b0e41c38a94c282ca9bdafe"
          },
          "parent": null,
          "content": {
            "src": "https://resource2.heygen.ai/video/bc0b766f20e84136acfaf40b2dfc70b5/original.mp4",
            "trim": {
              "end_offset": 0.0,
              "start_offset": 0.0
            },
            "type": "url",
            "volume": 1.0,
            "playback": "full_video",
            "speed_multiplier": null
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": {
                "top": 0.0,
                "left": 0.0,
                "right": 0.0,
                "bottom": 0.0
              },
              "scale": {
                "x": 1.0,
                "y": 1.0
              }
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": {
              "rotate": null
            },
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": "093c8bb090824fd5b5c7531b37c36bb5"
        },
        "HTn4ew51": {
          "id": "HTn4ew51",
          "type": "interactive",
          "assets": null,
          "parent": null,
          "content": {
            "base_props": {
              "x": 0.5,
              "y": 0,
              "color": "#000000",
              "width": "50%",
              "height": "100%",
              "layout": "right",
              "blockVideo": true,
              "fontFamily": "Arial",
              "borderRadius": 0,
              "backgroundColor": "#661e60"
            },
            "component_id": "interactive_quiz",
            "component_props": {
              "theme": "dark",
              "title": "O que você faz primeiro?",
              "options": [
                {
                  "id": "default-option-1",
                  "text": "A. Mantém a atividade para não dar visibilidade ao episódio e conversa com a turma outro dia.",
                  "feedback": "Resposta Incorreta!",
                  "isCorrect": false
                },
                {
                  "id": "default-option-2",
                  "text": "B. Interrompe a conduta, protege o estudante de nova exposição, estabelece o limite de forma\nfirme e serena e informa que fará os encaminhamentos previstos.",
                  "feedback": "Parabéns, você conduziu da maneira correta.",
                  "isCorrect": true
                },
                {
                  "id": "default-option-3",
                  "text": "C. Pede que os próprios estudantes resolvam o conflito, pois desenvolver autonomia também\nfaz parte da aprendizagem.",
                  "feedback": "Resposta Incorreta!",
                  "isCorrect": false
                }
              ],
              "nextText": "Continuar",
              "columnNum": 1,
              "submitText": "Responder",
              "correctColor": "#1E7220",
              "buttonBgColor": "#FFFFFF",
              "optionBgColor": "#FFFFFF",
              "titleFontSize": 48,
              "correctBgColor": "#EBFAEB",
              "incorrectColor": "#A41E27",
              "optionFontSize": 32,
              "buttonTextColor": "#171717",
              "headerTextColor": "#FFFFFF",
              "optionTextColor": "#333333",
              "incorrectBgColor": "#FFECE8",
              "optionOutlineColor": "#EDEDED",
              "previewSelectedIndex": null,
              "requireCorrectAnswer": true,
              "brand_color_text_role": "primary",
              "brand_color_outline_role": "tertiary",
              "brand_color_option_bg_role": "secondary"
            },
            "interactivity_type": "component"
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": {
                "top": null,
                "left": null,
                "right": null,
                "bottom": null
              },
              "scale": {
                "x": 1.0,
                "y": 1.0
              }
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": {
              "rotate": {
                "angle": 0.0
              }
            },
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": null
        },
        "KqE4943S": {
          "id": "KqE4943S",
          "type": "scene",
          "assets": null,
          "parent": null,
          "content": {
            "captions": [],
            "elements": [
              "NYoi9nt5"
            ],
            "background": null,
            "next_scene": null,
            "layout_name": null,
            "scene_effects": [],
            "background_color": "#FFFFFF",
            "brand_color_role": null,
            "cascade_animations": null,
            "default_scene_animations": null
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": null,
              "scale": null
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": null,
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": null
        },
        "NYoi9nt5": {
          "id": "NYoi9nt5",
          "type": "avatar",
          "assets": null,
          "parent": null,
          "content": {
            "alpha": null,
            "model": "tokyo_v2_1_dmd_rlhf",
            "engine": "avatar_v",
            "prompt": null,
            "matting": false,
            "avatar_id": "2d0d7a898328477d9f0e92a71fd840d0",
            "resolution": "1080p",
            "gesture_mp4": null,
            "render_type": "normal",
            "frame_offset": null,
            "gesture_webm": null,
            "inference_mp4": null,
            "talking_photo": {
              "crop": null,
              "emotion": null,
              "enhance": false,
              "expression": null
            },
            "inference_webm": null,
            "render_type_v2": "normal",
            "avatar_group_id": "ea087fe9606344c5bd3c86ec091672b0",
            "engine_settings": {
              "model": "tokyo_v2_2",
              "resolution": "1080p",
              "engine_type": "cross_ref",
              "cross_ref_avatar_id": null
            },
            "inference_job_id": null,
            "avatar_background": null,
            "circle_background": "#f6f6fc",
            "avatar_artifact_id": null,
            "use_unlimited_mode": null,
            "cross_ref_avatar_id": null,
            "spotlight_image_url": null,
            "use_avatar_iv_model": true,
            "inference_packed_mp4": null,
            "keep_original_prompt": null,
            "spotlight_mode_width": null,
            "enable_spotlight_mode": null,
            "spotlight_mode_height": null,
            "use_third_party_model": null,
            "third_party_motion_type": null,
            "third_party_model_prompt": null,
            "avatar_iv_more_expressive": true,
            "enforce_legacy_talking_photo_inference": null
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": {
                "top": 0.0,
                "left": 0.0,
                "right": 0.0,
                "bottom": 0.0
              },
              "scale": {
                "x": 0.703125,
                "y": 0.703125
              }
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": {
              "rotate": {
                "angle": 0.0
              }
            },
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": null
        },
        "QkCq0RZd": {
          "id": "QkCq0RZd",
          "type": "avatar",
          "assets": null,
          "parent": null,
          "content": {
            "alpha": null,
            "model": "tokyo_v2_1_dmd_rlhf",
            "engine": "avatar_v",
            "prompt": null,
            "matting": false,
            "avatar_id": "2d0d7a898328477d9f0e92a71fd840d0",
            "resolution": "1080p",
            "gesture_mp4": null,
            "render_type": "normal",
            "frame_offset": null,
            "gesture_webm": null,
            "inference_mp4": null,
            "talking_photo": {
              "crop": null,
              "emotion": null,
              "enhance": false,
              "expression": null
            },
            "inference_webm": null,
            "render_type_v2": "normal",
            "avatar_group_id": "ea087fe9606344c5bd3c86ec091672b0",
            "engine_settings": {
              "model": "tokyo_v2_2",
              "resolution": "1080p",
              "engine_type": "cross_ref",
              "cross_ref_avatar_id": null
            },
            "inference_job_id": null,
            "avatar_background": null,
            "circle_background": "#f6f6fc",
            "avatar_artifact_id": null,
            "use_unlimited_mode": null,
            "cross_ref_avatar_id": null,
            "spotlight_image_url": null,
            "use_avatar_iv_model": true,
            "inference_packed_mp4": null,
            "keep_original_prompt": null,
            "spotlight_mode_width": null,
            "enable_spotlight_mode": null,
            "spotlight_mode_height": null,
            "use_third_party_model": null,
            "third_party_motion_type": null,
            "third_party_model_prompt": null,
            "avatar_iv_more_expressive": true,
            "enforce_legacy_talking_photo_inference": null
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": {
                "top": 0.0,
                "left": 0.0,
                "right": 0.0,
                "bottom": 0.0
              },
              "scale": {
                "x": 0.703125,
                "y": 0.703125
              }
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": {
              "rotate": {
                "angle": 0.0
              }
            },
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": null
        },
        "Rf6coP7k": {
          "id": "Rf6coP7k",
          "type": "scene",
          "assets": null,
          "parent": null,
          "content": {
            "captions": [],
            "elements": [],
            "background": {
              "type": "video",
              "value": "6SVkeGR7"
            },
            "next_scene": null,
            "layout_name": null,
            "scene_effects": [],
            "background_color": "#FFFFFF",
            "brand_color_role": null,
            "cascade_animations": null,
            "default_scene_animations": null
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": {
                "top": null,
                "left": null,
                "right": null,
                "bottom": null
              },
              "scale": {
                "x": 1.0,
                "y": 1.0
              }
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": {
              "rotate": {
                "angle": 0.0
              }
            },
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": null
        },
        "WKnYo0d9": {
          "id": "WKnYo0d9",
          "type": "avatar",
          "assets": null,
          "parent": null,
          "content": {
            "alpha": null,
            "model": "tokyo_v2_1_dmd_rlhf",
            "engine": "avatar_v",
            "prompt": null,
            "matting": false,
            "avatar_id": "2d0d7a898328477d9f0e92a71fd840d0",
            "resolution": "1080p",
            "gesture_mp4": "",
            "render_type": "normal",
            "frame_offset": null,
            "gesture_webm": "",
            "inference_mp4": "",
            "talking_photo": {
              "crop": null,
              "emotion": null,
              "enhance": false,
              "expression": null
            },
            "inference_webm": "",
            "render_type_v2": "normal",
            "avatar_group_id": "ea087fe9606344c5bd3c86ec091672b0",
            "engine_settings": {
              "model": "tokyo_v2_2",
              "resolution": "1080p",
              "engine_type": "cross_ref",
              "cross_ref_avatar_id": null
            },
            "inference_job_id": "",
            "avatar_background": null,
            "circle_background": "#f6f6fc",
            "avatar_artifact_id": null,
            "use_unlimited_mode": null,
            "cross_ref_avatar_id": null,
            "spotlight_image_url": null,
            "use_avatar_iv_model": true,
            "inference_packed_mp4": "",
            "keep_original_prompt": null,
            "spotlight_mode_width": null,
            "enable_spotlight_mode": null,
            "spotlight_mode_height": null,
            "use_third_party_model": null,
            "third_party_motion_type": null,
            "third_party_model_prompt": null,
            "avatar_iv_more_expressive": true,
            "enforce_legacy_talking_photo_inference": null
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": {
                "top": 0.0,
                "left": 0.0,
                "right": 0.0,
                "bottom": 0.0
              },
              "scale": {
                "x": 0.703125,
                "y": 0.703125
              }
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": {
              "rotate": {
                "angle": 0.0
              }
            },
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": null
        },
        "X7WZfDph": {
          "id": "X7WZfDph",
          "type": "scene",
          "assets": null,
          "parent": null,
          "content": {
            "captions": [],
            "elements": [
              "WKnYo0d9",
              "HTn4ew51"
            ],
            "background": null,
            "next_scene": null,
            "layout_name": null,
            "scene_effects": [],
            "background_color": "#FFFFFF",
            "brand_color_role": null,
            "cascade_animations": null,
            "default_scene_animations": null
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": null,
              "scale": null
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": null,
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": null
        },
        "blqvIoz7": {
          "id": "blqvIoz7",
          "type": "avatar",
          "assets": null,
          "parent": null,
          "content": {
            "alpha": null,
            "model": "tokyo_v2_1_dmd_rlhf",
            "engine": "avatar_v",
            "prompt": null,
            "matting": false,
            "avatar_id": "2d0d7a898328477d9f0e92a71fd840d0",
            "resolution": "1080p",
            "gesture_mp4": "",
            "render_type": "normal",
            "frame_offset": null,
            "gesture_webm": "",
            "inference_mp4": "",
            "talking_photo": {
              "crop": null,
              "emotion": null,
              "enhance": false,
              "expression": null
            },
            "inference_webm": "",
            "render_type_v2": "normal",
            "avatar_group_id": "ea087fe9606344c5bd3c86ec091672b0",
            "engine_settings": {
              "model": "tokyo_v2_2",
              "resolution": "1080p",
              "engine_type": "cross_ref",
              "cross_ref_avatar_id": null
            },
            "inference_job_id": "",
            "avatar_background": null,
            "circle_background": "#f6f6fc",
            "avatar_artifact_id": null,
            "use_unlimited_mode": null,
            "cross_ref_avatar_id": null,
            "spotlight_image_url": null,
            "use_avatar_iv_model": true,
            "inference_packed_mp4": "",
            "keep_original_prompt": null,
            "spotlight_mode_width": null,
            "enable_spotlight_mode": null,
            "spotlight_mode_height": null,
            "use_third_party_model": null,
            "third_party_motion_type": null,
            "third_party_model_prompt": null,
            "avatar_iv_more_expressive": true,
            "enforce_legacy_talking_photo_inference": null
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": {
                "top": 0.0,
                "left": 0.0,
                "right": 0.0,
                "bottom": 0.0
              },
              "scale": {
                "x": 0.703125,
                "y": 0.703125
              }
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": {
              "rotate": {
                "angle": 0.0
              }
            },
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": null
        },
        "eA4fQhYp": {
          "id": "eA4fQhYp",
          "type": "scene",
          "assets": null,
          "parent": null,
          "content": {
            "captions": [],
            "elements": [
              "3uh8ldCz"
            ],
            "background": null,
            "next_scene": null,
            "layout_name": null,
            "scene_effects": [],
            "background_color": "#FFFFFF",
            "brand_color_role": null,
            "cascade_animations": null,
            "default_scene_animations": null
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": null,
              "scale": null
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": null,
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": null
        },
        "iOOYv8s5": {
          "id": "iOOYv8s5",
          "type": "scene",
          "assets": null,
          "parent": null,
          "content": {
            "captions": [],
            "elements": [
              "blqvIoz7"
            ],
            "background": null,
            "next_scene": null,
            "layout_name": null,
            "scene_effects": [],
            "background_color": "#FFFFFF",
            "brand_color_role": null,
            "cascade_animations": null,
            "default_scene_animations": null
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": null,
              "scale": null
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": null,
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": null
        },
        "oCwemNJp": {
          "id": "oCwemNJp",
          "type": "scene",
          "assets": null,
          "parent": null,
          "content": {
            "captions": [],
            "elements": [
              "QkCq0RZd"
            ],
            "background": null,
            "next_scene": null,
            "layout_name": null,
            "scene_effects": [],
            "background_color": "#FFFFFF",
            "brand_color_role": null,
            "cascade_animations": null,
            "default_scene_animations": null
          },
          "attributes": {
            "size": {
              "fit": "none",
              "crop": null,
              "scale": null
            },
            "opacity": 1.0,
            "position": {
              "type": "center",
              "offset": {
                "x": 0.0,
                "y": 0.0
              }
            },
            "animations": [],
            "transformation": null,
            "rounded_corners": null,
            "preserve_rounded_corners": false
          },
          "brand_kit_id": null
        }
      },
      "scene_effects": {
        "elements": {}
      }
    },
    "captions": {
      "motion": null,
      "elements": {},
      "global_config_id": null,
      "global_attributes": null,
      "motion_identity_id": null,
      "remove_punctuation": false
    },
    "structure": null,
    "alignments": {
      "3uh8ldCz": {
        "element_id": "3uh8ldCz",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "mnTUDS4M",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "mnTUDS4M",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": [],
        "scene_effect_alignments": null
      },
      "6SVkeGR7": {
        "element_id": "6SVkeGR7",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "yAgebs2q",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "yAgebs2q",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": null,
        "scene_effect_alignments": null
      },
      "HTn4ew51": {
        "element_id": "HTn4ew51",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "YvHFKVQC",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "YvHFKVQC",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": [],
        "scene_effect_alignments": null
      },
      "KqE4943S": {
        "element_id": "KqE4943S",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "XxU9GdYk",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "XxU9GdYk",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": null,
        "scene_effect_alignments": null
      },
      "NYoi9nt5": {
        "element_id": "NYoi9nt5",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "XxU9GdYk",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "XxU9GdYk",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": null,
        "scene_effect_alignments": null
      },
      "QkCq0RZd": {
        "element_id": "QkCq0RZd",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "rXmEkoGY",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "rXmEkoGY",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": [],
        "scene_effect_alignments": null
      },
      "Rf6coP7k": {
        "element_id": "Rf6coP7k",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "yAgebs2q",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "yAgebs2q",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": null,
        "scene_effect_alignments": null
      },
      "WKnYo0d9": {
        "element_id": "WKnYo0d9",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "YvHFKVQC",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "YvHFKVQC",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": [],
        "scene_effect_alignments": null
      },
      "X7WZfDph": {
        "element_id": "X7WZfDph",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "YvHFKVQC",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "YvHFKVQC",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": [],
        "scene_effect_alignments": null
      },
      "blqvIoz7": {
        "element_id": "blqvIoz7",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "2MedGmgD",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "2MedGmgD",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": [],
        "scene_effect_alignments": null
      },
      "eA4fQhYp": {
        "element_id": "eA4fQhYp",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "mnTUDS4M",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "mnTUDS4M",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": [],
        "scene_effect_alignments": null
      },
      "iOOYv8s5": {
        "element_id": "iOOYv8s5",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "2MedGmgD",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "2MedGmgD",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": [],
        "scene_effect_alignments": null
      },
      "oCwemNJp": {
        "element_id": "oCwemNJp",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": null,
            "script_id": "rXmEkoGY",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "rXmEkoGY",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": [],
        "scene_effect_alignments": null
      },
      "heygen-66286d310c9e494c8453e17c9b1429c2-0VkDxF0O": {
        "element_id": "heygen-66286d310c9e494c8453e17c9b1429c2-0VkDxF0O",
        "infer_audio": false,
        "alignment_info": {
          "end": {
            "pinned": false,
            "script_id": "mnTUDS4M",
            "word_index": -1
          },
          "start": {
            "pinned": null,
            "script_id": "XxU9GdYk",
            "word_index": 0
          }
        },
        "gesture_alignments": null,
        "animation_alignments": null,
        "scene_effect_alignments": null
      }
    },
    "background_audio": {
      "elements": {
        "heygen-66286d310c9e494c8453e17c9b1429c2-0VkDxF0O": {
          "id": "heygen-66286d310c9e494c8453e17c9b1429c2-0VkDxF0O",
          "type": "background_audio",
          "attributes": {
            "src": "https://files2.heygen.ai/prod/movio/preset/audio/heygen_music/66286d310c9e494c8453e17c9b1429c2.wav",
            "ease": {
              "ease_in": 0.0,
              "ease_out": 0.0
            },
            "loop": false,
            "volume": 0.05,
            "source_type": "url"
          }
        }
      }
    }
  },
  "video_output": {
    "fps": 25.0,
    "caption": false,
    "playback": {
      "speed": 1.0,
      "source": "default"
    },
    "resolution": {
      "width": 3840,
      "height": 2160
    },
    "scene_id_map": {}
  }
};
