// Segment metadata for Interactive Video
// Auto-generated by SCORM export
// Video ID: cd60d2823d4049f0b13c28bbb1b4b13e

window.SEGMENT_METADATA = [
  {
    "segmentId": "default",
    "videoId": "cd60d2823d4049f0b13c28bbb1b4b13e",
    "sceneIds": [
      "KqE4943S",
      "iOOYv8s5",
      "Rf6coP7k",
      "oCwemNJp",
      "X7WZfDph",
      "eA4fQhYp"
    ],
    "videoUrl": "default.mp4"
  }
];
