import { ArrowDown, ArrowUpRight, Check, Plus } from 'lucide-react';
import { Action, Icon, Logo, SectionHeading } from './brand';
import { DemoGate, LearningPaths, VideoPlayer } from './interactive';
import { contact, faq, methods, process, solutions, websiteCases } from '@/data/content';

export function ClientLogos() {
  return <section className="client-band" aria-label="Marcas e projetos"><div className="container"><p>Marcas que transformaram<br/><strong>conhecimento em experiência.</strong></p><div className="client-logos">{[['heineken','Heineken'],['spsul','SPSul'],['incerti','Incerti Automotivos'],['atacadao','Atacadão das Baterias'],['brutus','Brutus'],['metatrade','MetaTrade']].map(([file,name]) => <img key={file} src={`/assets/img/logos/${file}.png`} alt={name} width="200" height="66" loading="lazy"/>)}</div></div></section>;
}

export function Services() {
  return <section className="section services" id="solucoes"><div className="container"><SectionHeading label="O QUE A DELUMO FAZ" title={<>Soluções para<br/><em>sua empresa.</em></>}><p>Desenvolvemos o conteúdo, a experiência e a plataforma. Cada solução pode funcionar sozinha ou fazer parte do mesmo projeto.</p></SectionHeading><div className="ds-service-grid">{solutions.map(item => <a href={`/solucoes/${item.slug}`} className="ds-service-item tp_fade_anim" key={item.slug}><div className="ds-service-item-box"><div className="ds-service-item-icon"><Icon name={item.icon} size={34}/><span>{item.number}</span></div><h3>{item.name}</h3><p>{item.short}</p><div className="ds-service-item-bottom"><span>Ver aplicações e entregas</span><span className="ds-service-item-btn"><ArrowUpRight size={22}/></span></div></div></a>)}</div><p className="solution-help">Não sabe por onde começar? <a href="/contato">Converse com Guto Luz <ArrowUpRight size={16}/></a></p></div></section>;
}

export function TrainingSection() {
  return <section className="section training-section" id="treinamentos"><div className="container">
    <SectionHeading label="TREINAMENTOS E TRILHAS" title={<>Aprendizagem conectada<br/><em>à rotina da equipe.</em></>}><p>Transformamos o conteúdo da empresa em aulas, prática e avaliações. As trilhas organizam o percurso de cada função, da integração à atualização profissional.</p></SectionHeading>
    <LearningPaths/>
    <details className="content-disclosure" id="metodo"><summary><span>Metodologias de aprendizagem</span><Plus size={20}/></summary><div className="disclosure-body"><p>Escolhemos os métodos conforme o público e o que ele precisa aprender e aplicar.</p><div className="methods-grid">{methods.map(method => <article key={method.title} className="method-item"><Icon name={method.icon}/><div><h4>{method.title}</h4><p>{method.text}</p></div></article>)}</div></div></details>
    <details className="content-disclosure"><summary><span>Exemplos de treinamentos com avatares</span><Plus size={20}/></summary><div className="disclosure-body"><TrainingVideos embedded/></div></details>
  </div></section>;
}

export function PlatformsSection() {
  return <section className="section platforms-section" id="plataforma-de-ensino"><div className="container">
    <SectionHeading label="PLATAFORMA PERSONALIZADA" title={<>Um lugar para ensinar.<br/><em>Uma visão de cada aluno.</em></>} light><p>Além dos treinamentos, desenvolvemos o ambiente para disponibilizar as aulas e acompanhar a aprendizagem, com a identidade e as necessidades da empresa.</p></SectionHeading>
    <div className="platform-layout"><div className="learning-platform tp_fade_anim">
      <img src="/media/immersive-team.webp" alt="Representação de aprendizagem em equipe com realidade virtual" width="1774" height="887" loading="lazy"/>
      <h3>Do conteúdo ao acompanhamento.</h3>
      <p>Trilhas para novos colaboradores e equipes atuais, organizadas por cargo, setor ou unidade.</p>
    </div><div className="platform-features">{[
      ['GraduationCap','Aulas e trilhas','Vídeos, avatares, materiais de apoio e avaliações em percursos definidos para cada equipe.'],
      ['ChartNoAxesCombined','Evolução dos alunos','Gestão de turmas e acesso por perfil. Relatórios de participação, progresso e conclusão conforme o projeto.'],
      ['Network','Integração com ERP e RH','Desenvolvemos a API para conectar cadastros e registros ao ERP ou aplicativo de RH, conforme a viabilidade técnica.'],
      ['BrainCircuit','Agentes de IA','Assistentes para localizar conteúdos e responder dúvidas com uma base aprovada pela empresa.'],
    ].map(([icon,title,text]) => <article key={title}><Icon name={icon} size={27}/><div><h3>{title}</h3><p>{text}</p></div></article>)}<Action href="/solucoes/plataformas">Conheça a plataforma sob medida</Action></div></div>
    <p className="platform-footnote">Desenvolvimento em Next.js, acesso responsivo e recursos definidos para cada projeto.</p>
  </div></section>;
}

export function FeaturedProjects({ heading = true, compact = false }: { heading?: boolean; compact?: boolean }) {
  return <div className={`featured-projects ${compact ? 'is-compact' : ''}`}>
    <section className="section conquest-section" id="conquistahnk"><div className="container">{heading && <SectionHeading label="PROJETOS EM AÇÃO" title={<>Games e experiências<br/><em>desenvolvidos pela Delumo.</em></>}><p>Conheça aplicações de gamificação e realidade virtual em projetos para empresas.</p></SectionHeading>}<div className="feature-grid"><div className="feature-media tp_fade_anim"><VideoPlayer id="xxzRgpooGUM" poster="/media/conquista.webp" title="ConquistaHNK: Projeto Tamanduá"/></div><article className="feature-copy"><p className="eyebrow">GAMIFICAÇÃO / SPSUL</p><div className="project-title"><img src="/assets/img/logo-conquistahnk.png" width="72" height="72" alt="Logo ConquistaHNK" loading="lazy"/><h2>ConquistaHNK</h2></div><p>Metas comerciais viram missões, pontos de venda viram territórios e cada avanço aparece no ranking. Um game que conecta execução em campo, estratégia e reconhecimento.</p><div className="project-facts"><span><strong>33</strong>revendas Heineken</span><span><strong>4 estados</strong>SP, PR, SC e RS</span></div><Action href="https://www.conquistahnk.com.br" external secondary>conquistahnk.com.br</Action></article></div></div></section>
    <section className="hotzone-section" id="avante-hotzone"><img className="hotzone-background" src="/assets/img/avante-hotzone-bg.webp" alt="" width="1600" height="893" loading="lazy"/><div className="hotzone-film"/><div className="container hotzone-content"><img className="hotzone-logo tp_fade_anim" src="/assets/img/logo-avante-hotzone.webp" alt="Avante HotZone, Rumo ao Gol SPSul" width="260" height="253" loading="lazy"/><div className="hotzone-copy"><p className="eyebrow">GAMIFICAÇÃO / SPSUL</p><h2>Avante HotZone</h2><p className="hotzone-lead">A estratégia entra em campo.<br/>O time joga junto.</p><p>Um campeonato de execução comercial em que cada território se torna um campo de jogo. Metas, rodadas e rankings organizam as prioridades e mostram a evolução da equipe.</p>{!compact && <p>Vendedores acompanham seu farol diário. Supervisores, gerentes e Trade atuam como comissão técnica, conectando indicadores à ação nos pontos de venda.</p>}<ul className="inline-checks"><li><Check size={16}/> Metas e missões</li><li><Check size={16}/> Farol diário</li><li><Check size={16}/> Ranking por rodada</li></ul><Action href="https://www.avantehotzone.com.br" external>avantehotzone.com.br</Action></div></div></section>
    <section className="section metatrade-section" id="metatrade"><div className="container"><div className="feature-grid reverse"><article className="feature-copy"><p className="eyebrow">IMERSÃO / TREINAMENTO / 3D</p><div className="project-title"><img src="/assets/img/logo-metatrade.png" width="90" height="90" alt="Logo MetaTrade" loading="lazy"/><h2>MetaTrade</h2></div><p className="project-credit">Desenvolvido para a <a href="https://www.realizacoeshumanas.com.br" target="_blank" rel="noopener noreferrer">Realizações Humanas</a>, para a Companhia Heineken.</p><p>O ponto de venda se transforma em um ambiente de aprendizagem. Produtos, materiais de comunicação e padrões de execução aparecem no lugar certo, em seis cenários navegáveis.</p>{!compact && <p>Uma experiência para observar, explorar e aplicar o conhecimento por computador, celular ou óculos de realidade virtual, conforme o dispositivo.</p>}<div className="project-facts"><span><strong>6 ambientes</strong>do bar à conveniência</span><span><strong>360°</strong>de navegação imersiva</span></div></article><div className="feature-media tp_fade_anim"><VideoPlayer id="-C6du1R1xyg" poster="/media/metatrade-video.webp" title="MetaTrade: conheça a experiência"/><DemoGate/></div></div>{!compact && <div className="field-gallery"><figure><img src="/assets/img/treinamento-metatrade.jpg" alt="Treinamento presencial MetaTrade com participantes usando óculos de realidade virtual" width="900" height="600" loading="lazy"/><figcaption>Aprendizagem aplicada em uma experiência presencial.</figcaption></figure><figure><img src="/assets/img/uniforme-metatrade.jpg" alt="Identidade do projeto MetaTrade aplicada aos uniformes da equipe" width="900" height="600" loading="lazy"/><figcaption>Identidade e experiência conectadas ao projeto.</figcaption></figure><div className="field-statement"><Icon name="ScanEye" size={42}/><h3>O conteúdo ganha contexto.<br/>A experiência ganha sentido.</h3><a href="/solucoes/imersao" className="text-link">Explore as soluções imersivas <ArrowUpRight size={18}/></a></div></div>}{compact && <a className="text-link project-more" href="/projetos#metatrade">Mais sobre os projetos <ArrowUpRight size={18}/></a>}</div></section>
  </div>;
}

export function TrainingVideos({ embedded = false }: { embedded?: boolean }) {
  const examples = <div className="video-examples"><article><VideoPlayer id="XFXbMmj8w0E" poster="/media/avatar.webp" title="Código de Conduta"/><div className="video-example-caption"><h3>Cultura e conduta</h3><span>Avatar de IA e narrativa visual</span></div></article><article><VideoPlayer id="OYASF7Wgz-s" poster="/media/integracao.webp" title="Integração de novos colaboradores"/><div className="video-example-caption"><h3>Integração de equipes</h3><span>Conteúdo por função</span></div></article></div>;
  if (embedded) return <div className="training-examples"><p>Apresentações e manuais transformados em videoaulas, com roteiro, identidade visual e revisão da empresa.</p>{examples}</div>;
  return <section className="section training-videos"><div className="container"><SectionHeading label="EXEMPLOS DE TREINAMENTOS" title={<>Conteúdo da empresa.<br/><em>Novas formas de ensinar.</em></>}/>{examples}</div></section>;
}

export function WebsiteCases({ compact = false }: { compact?: boolean }) {
  return <section className={`section website-cases ${compact ? 'is-compact' : ''}`} id="sites"><div className="container"><SectionHeading label="SITES E PLATAFORMAS" title={<>Sites e plataformas<br/><em>para empresas.</em></>}><p>Informação organizada, identidade consistente e uma jornada que ajuda o visitante a encontrar o que precisa.</p></SectionHeading><div className="website-grid">{websiteCases.map(item => <article className="website-case tp_fade_anim" key={item.slug}><a className="website-image" href={item.url} target="_blank" rel="noopener noreferrer" aria-label={`Visitar ${item.title}`}><img src={item.image} alt={`Página inicial do site ${item.title}`} width="1440" height="900" loading="lazy"/><span className="website-arrow"><ArrowUpRight size={24}/></span></a><p className="eyebrow">{item.category}</p><h3><a href={item.url} target="_blank" rel="noopener noreferrer">{item.title}</a></h3><p>{item.text}</p><a className="text-link" href={item.url} target="_blank" rel="noopener noreferrer">{item.domain}<ArrowUpRight size={16}/></a></article>)}</div></div></section>;
}

export function ProcessSection() {
  return <section className="section process-section" id="como-fazemos"><div className="container"><SectionHeading label="COMO CONSTRUÍMOS" title={<>Como o projeto<br/><em>acontece.</em></>} light><p>Um processo colaborativo, com clareza de escopo, aprovação de conteúdo e tecnologia escolhida para a necessidade da empresa.</p></SectionHeading><ol className="process-list">{process.map((step,i) => <li className="tp_fade_anim" key={step.title}><span>0{i+1}</span><h3>{step.title}</h3><p>{step.text}</p></li>)}</ol></div></section>;
}

export function FAQ() {
  return <section className="section faq-section"><div className="container faq-layout"><div><p className="eyebrow">PERGUNTAS FREQUENTES</p><h2>Dúvidas frequentes</h2><Action href="/contato" secondary>Converse com a Delumo</Action></div><div className="faq-list">{faq.map(([question,answer],i) => <details key={question}><summary><small>0{i+1}</small><h3>{question}</h3><Plus size={20}/></summary><p>{answer}</p></details>)}</div></div></section>;
}

export function ContactCTA() {
  return <section className="contact-cta"><div className="container"><p className="eyebrow">SEU PRÓXIMO PROJETO COMEÇA AQUI</p><h2>Vamos conversar<br/><em>sobre seu projeto?</em></h2><Action href={contact.whatsapp} external>Converse com Guto Luz</Action><p className="cta-contact"><a href="tel:+5554981302517">{contact.phone}</a><a href={`mailto:${contact.email}`}>{contact.email}</a></p><div className="cta-down"><ArrowDown size={24}/></div></div></section>;
}

export function Footer() {
  return <footer className="site-footer"><div className="container"><div className="footer-top"><div><a href="/" aria-label="Delumo, início"><Logo/></a><p>Conhecimento, tecnologia<br/>e experiências para evoluir.</p></div><nav aria-label="Soluções no rodapé"><h3>Soluções</h3>{solutions.map(item=><a href={`/solucoes/${item.slug}`} key={item.slug}>{item.name}</a>)}</nav><nav aria-label="Empresa no rodapé"><h3>Delumo</h3><a href="/sobre">Quem somos</a><a href="/projetos">Projetos</a><a href="/contato">Contato</a><a href="/privacidade">Privacidade</a></nav><div className="footer-contact"><h3>Vamos conversar</h3><a href={contact.whatsapp} target="_blank" rel="noopener noreferrer">{contact.name}<br/>{contact.phone}<ArrowUpRight size={18}/></a><a href={`mailto:${contact.email}`}>{contact.email}</a><p>Rua Anita Garibaldi, 1473<br/>Bela Vista, Erechim, RS</p></div></div><div className="powered"><span>POWERED</span><Logo/></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Delumo. Todos os direitos reservados.</span><span>De Erechim para novas possibilidades.</span><a href="#top">Voltar ao topo <ArrowUpRight size={16}/></a></div></div></footer>;
}
