import { ArrowDown, ArrowUpRight, ChevronDown, ChevronRight, Check, LockKeyhole } from 'lucide-react';
import { Action, Icon, SectionHeading } from './brand';
import { ContactCTA } from './sections';
import { VideoPlayer } from './interactive';
import LearningQuiz from './learning-quiz';
import { academyCourses, learningDeliverables, trainingSectors } from '@/data/learning';

const nrSource = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-1';

export default function TrainingDetail() {
  return <main id="main" className="training-detail-page">
    <section className="inner-hero"><div className="container"><nav className="breadcrumbs" aria-label="Caminho de navegação"><a href="/">Início</a><ChevronRight size={14}/><a href="/#solucoes">Soluções</a><ChevronRight size={14}/><span aria-current="page">Treinamentos e trilhas</span></nav><h1>Treinamentos e trilhas</h1><p>O conhecimento da sua empresa, organizado para quem precisa colocar em prática.</p><nav className="solution-jumps" aria-label="Nesta solução"><a href="#academia-esb">Case AcademiaESB <ArrowDown size={15}/></a><a href="#aplicacoes">Treinamentos por setor <ArrowDown size={15}/></a><a href="#entregas">Como desenvolvemos <ArrowDown size={15}/></a></nav></div></section>

    <section className="section academy-case" id="academia-esb"><div className="container">
      <SectionHeading label="CASE ESB LIGHT" title={<>Conhecer o produto.<br/><em>Qualificar a conversa.</em></>}><p>Na ESB Light, o site institucional conecta portfólio, aplicações e cases à AcademiaESB. Desenvolvemos a trilha para aprofundar o conhecimento técnico dos vendedores e apoiar uma argumentação comercial mais consistente.</p></SectionHeading>
      <div className="academy-overview"><p>Três cursos conduzem o aluno dos fundamentos às especificações e à aplicação do portfólio. Acesso individual e acompanhamento do progresso ajudam cada pessoa a avançar no próprio percurso.</p><a className="text-link" href="https://www.esblight.com.br/academiaesb" target="_blank" rel="noopener noreferrer">Conheça a AcademiaESB <ArrowUpRight size={17}/></a></div>
      <div className="course-flow" aria-label="Fluxograma da trilha AcademiaESB">
        <div className="flow-start"><LockKeyhole size={18}/><strong>Acesso individual</strong><span>Trilha de conhecimento</span></div>
        <div className="course-branches">{academyCourses.map((course, index) => <details className="course-node" key={course.title}>
          <summary><span className="course-number">0{index + 1}</span><span><small>CURSO {index + 1}</small><h3>{course.title}</h3><p>{course.description}</p><span className="course-count">{course.modules.length} módulos{course.intro ? ' + abertura' : ''}{course.supplement ? ' e complemento' : ''}</span></span><ChevronDown size={20}/></summary>
          <div className="course-modules">{course.intro && <p className="course-opening">{course.intro}</p>}<ol>{course.modules.map((module, moduleIndex) => <li key={module}><span>{String(moduleIndex + 1).padStart(2, '0')}</span>{module}</li>)}</ol>{course.supplement && <p className="course-supplement">Complemento: {course.supplement}</p>}</div>
        </details>)}</div>
        <div className="flow-end"><Check size={19}/><strong>Aplicação no atendimento e na venda consultiva</strong></div>
      </div>
      <div className="academy-video-layout"><VideoPlayer id="p85htFZYfu8" poster="/media/academia-esb-video.webp" title="Introdução à AcademiaESB"/><div><p className="eyebrow">DO ROTEIRO À VIDEOAULA</p><h3>Conteúdo técnico.<br/>Uma linguagem próxima.</h3><p>O vídeo de introdução apresenta a jornada da AcademiaESB. Roteiro, avatar e recursos visuais organizam o conteúdo para facilitar a compreensão e a consulta.</p><p>O mesmo processo pode transformar os materiais e o conhecimento dos especialistas da sua empresa em aulas alinhadas à rotina de cada função.</p></div></div>
    </div></section>

    <section className="section sector-section" id="aplicacoes"><div className="container"><SectionHeading label="TREINAMENTOS POR SETOR" title={<>Cada equipe aprende<br/><em>o que precisa aplicar.</em></>}><p>Uma base comum para a empresa, com trilhas exclusivas por setor, cargo, unidade ou rede. Novos colaboradores e equipes atuais recebem percursos adequados ao seu momento.</p></SectionHeading><div className="sector-grid">{trainingSectors.map(sector => <article id={sector.id} className="sector-item" key={sector.id}><Icon name={sector.icon} size={30}/><h3>{sector.title}</h3><p>{sector.text}</p></article>)}</div></div></section>

    <section className="section learning-production" id="entregas"><div className="container"><SectionHeading label="PESQUISA E DESENVOLVIMENTO" title={<>Sua realidade orienta<br/><em>cada etapa da criação.</em></>}><p>O trabalho começa com um estudo feito junto ao cliente. Compreendemos as necessidades da operação antes de escolher a linguagem, a metodologia e a tecnologia.</p></SectionHeading><div className="learning-deliverables">{learningDeliverables.map((item, index) => <article key={item.title}><span className="step-index">0{index + 1}</span><Icon name={item.icon}/><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><p className="learning-methods">Aprendizagem de adultos, microlearning, prática guiada e simulações podem ser combinados conforme o objetivo. Apresentações, manuais e procedimentos existentes são aproveitados e reorganizados com revisão do cliente.</p></div></section>

    <section className="section learning-platform-section"><div className="container"><SectionHeading label="PLATAFORMA DA SUA EMPRESA" title={<>Ensinar, acompanhar<br/><em>e evoluir.</em></>} light><p>Também desenvolvemos o ambiente onde os treinamentos acontecem: identidade própria, acesso individual e recursos definidos conforme as necessidades da empresa.</p></SectionHeading><div className="platform-capabilities">{[
      ['Users', 'Cada aluno, um percurso', 'Perfis de acesso, cursos por função, pré-requisitos e trilhas exclusivas por setor.'],
      ['ChartNoAxesCombined', 'Acompanhamento que orienta', 'Participação, progresso, resultados de quizzes e conclusão por pessoa e equipe.'],
      ['Network', 'Integrações sob medida', 'APIs para ERP, aplicativo de RH ou sistemas de gestão de riscos ocupacionais, conforme viabilidade, escopo e permissões.'],
    ].map(([icon, title, text]) => <article key={title}><Icon name={icon}/><h3>{title}</h3><p>{text}</p></article>)}</div><p className="integration-note">Conectamos os registros necessários ao acompanhamento dos treinamentos, com controles de acesso e tratamento de dados definidos no projeto. Não é preciso expor dados de saúde individuais para organizar uma trilha.</p><Action href="/contato?solucao=treinamentos">Planejar minha plataforma e trilhas</Action></div></section>

    <section className="section quiz-section" id="avaliacao"><div className="container quiz-layout"><div><p className="eyebrow">AVALIAÇÃO E FEEDBACK</p><h2>O que foi aprendido?<br/><em>O quiz ajuda a entender.</em></h2><p>Ao final de cada trilha, podemos incluir um quiz para verificar a compreensão, mostrar feedback e orientar a revisão de conteúdos.</p><p>Na plataforma personalizada, os resultados podem integrar o acompanhamento individual. Nota mínima, tentativas e critérios de conclusão são definidos com o cliente.</p><p>Este exemplo demonstra a interação. Não é uma prova oficial da AcademiaESB nem uma certificação.</p></div><LearningQuiz/></div></section>

    <section className="section nr-learning"><div className="container nr-layout"><div><p className="eyebrow">NR-1 E PREVENÇÃO</p><h2>Capacitação conectada<br/>ao plano da empresa.</h2></div><div><p>A redação do capítulo 1.5 da NR-1, em vigor desde 26 de maio de 2026, inclui expressamente os fatores de risco psicossociais relacionados ao trabalho no gerenciamento de riscos ocupacionais.</p><p>A partir das necessidades identificadas pela empresa e pelos profissionais de SST, desenvolvemos conteúdos sobre comunicação, liderança, prevenção ao assédio, procedimentos e práticas de trabalho. As trilhas podem apoiar as ações educativas do plano de prevenção.</p><p className="nr-caution">Treinamentos e registros digitais não substituem a identificação e avaliação dos riscos, as medidas sobre a organização do trabalho nem as exigências específicas de capacitação de cada norma. O escopo deve ser validado pelos responsáveis técnicos da empresa.</p><a className="text-link" href={nrSource} target="_blank" rel="noopener noreferrer">Consultar a NR-1 no Ministério do Trabalho <ArrowUpRight size={16}/></a></div></div></section>
    <section className="section related-training"><div className="container related-solutions"><h2>Conecte a trilha a outras experiências</h2><nav aria-label="Soluções relacionadas"><a href="/solucoes/plataformas">Plataformas inteligentes <ArrowUpRight size={18}/></a><a href="/solucoes/imersao">Experiências imersivas <ArrowUpRight size={18}/></a></nav></div></section><ContactCTA/>
  </main>;
}
